// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: dish.proto

package dishpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_dish_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{0}
}

type IDMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDMessage) Reset() {
	*x = IDMessage{}
	mi := &file_dish_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDMessage) ProtoMessage() {}

func (x *IDMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDMessage.ProtoReflect.Descriptor instead.
func (*IDMessage) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{1}
}

func (x *IDMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescriptionResponse) Reset() {
	*x = DescriptionResponse{}
	mi := &file_dish_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescriptionResponse) ProtoMessage() {}

func (x *DescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescriptionResponse.ProtoReflect.Descriptor instead.
func (*DescriptionResponse) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{2}
}

func (x *DescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DescriptionResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type IdsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdsMessage) Reset() {
	*x = IdsMessage{}
	mi := &file_dish_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdsMessage) ProtoMessage() {}

func (x *IdsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdsMessage.ProtoReflect.Descriptor instead.
func (*IdsMessage) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{3}
}

func (x *IdsMessage) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Flavors       []*Flavor              `protobuf:"bytes,3,rep,name=flavors,proto3" json:"flavors,omitempty"`
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CurId         int64                  `protobuf:"varint,9,opt,name=curId,proto3" json:"curId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishRequest) Reset() {
	*x = DishRequest{}
	mi := &file_dish_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishRequest) ProtoMessage() {}

func (x *DishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishRequest.ProtoReflect.Descriptor instead.
func (*DishRequest) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{4}
}

func (x *DishRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *DishRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DishRequest) GetFlavors() []*Flavor {
	if x != nil {
		return x.Flavors
	}
	return nil
}

func (x *DishRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DishRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DishRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DishRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DishRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DishRequest) GetCurId() int64 {
	if x != nil {
		return x.CurId
	}
	return 0
}

type Flavor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishId        int64                  `protobuf:"varint,1,opt,name=dishId,proto3" json:"dishId,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flavor) Reset() {
	*x = Flavor{}
	mi := &file_dish_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flavor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flavor) ProtoMessage() {}

func (x *Flavor) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flavor.ProtoReflect.Descriptor instead.
func (*Flavor) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{5}
}

func (x *Flavor) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *Flavor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Flavor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flavor) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_dish_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{6}
}

func (x *PageRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *PageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*Record              `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_dish_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{7}
}

func (x *PageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,8,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	CategoryName  string                 `protobuf:"bytes,9,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_dish_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{8}
}

func (x *Record) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Record) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Record) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Record) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Record) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Record) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Record) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *Record) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type RecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordsResponse) Reset() {
	*x = RecordsResponse{}
	mi := &file_dish_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordsResponse) ProtoMessage() {}

func (x *RecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordsResponse.ProtoReflect.Descriptor instead.
func (*RecordsResponse) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{9}
}

func (x *RecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type DishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Flavors       []*Flavor              `protobuf:"bytes,4,rep,name=flavors,proto3" json:"flavors,omitempty"`
	Id            int64                  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,10,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishResponse) Reset() {
	*x = DishResponse{}
	mi := &file_dish_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishResponse) ProtoMessage() {}

func (x *DishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishResponse.ProtoReflect.Descriptor instead.
func (*DishResponse) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{10}
}

func (x *DishResponse) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *DishResponse) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *DishResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DishResponse) GetFlavors() []*Flavor {
	if x != nil {
		return x.Flavors
	}
	return nil
}

func (x *DishResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DishResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DishResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DishResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DishResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DishResponse) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type DishesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*DishResponse        `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishesResponse) Reset() {
	*x = DishesResponse{}
	mi := &file_dish_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishesResponse) ProtoMessage() {}

func (x *DishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishesResponse.ProtoReflect.Descriptor instead.
func (*DishesResponse) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{11}
}

func (x *DishesResponse) GetDishes() []*DishResponse {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	CurId         int64                  `protobuf:"varint,3,opt,name=curId,proto3" json:"curId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_dish_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dish_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_dish_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateRequest) GetCurId() int64 {
	if x != nil {
		return x.CurId
	}
	return 0
}

var File_dish_proto protoreflect.FileDescriptor

const file_dish_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"dish.proto\x12\adish.v1\"\x0f\n" +
	"\rEmptyResponse\"\x1b\n" +
	"\tIDMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"M\n" +
	"\x13DescriptionResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"\x1e\n" +
	"\n" +
	"IdsMessage\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"\xf8\x01\n" +
	"\vDishRequest\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x03R\n" +
	"categoryId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\aflavors\x18\x03 \x03(\v2\x0f.dish.v1.FlavorR\aflavors\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\a \x01(\x02R\x05price\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x14\n" +
	"\x05curId\x18\t \x01(\x03R\x05curId\"Z\n" +
	"\x06Flavor\x12\x16\n" +
	"\x06dishId\x18\x01 \x01(\x03R\x06dishId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\x89\x01\n" +
	"\vPageRequest\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"O\n" +
	"\fPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12)\n" +
	"\arecords\x18\x02 \x03(\v2\x0f.dish.v1.RecordR\arecords\"\xf6\x01\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x03 \x01(\x03R\n" +
	"categoryId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"updateTime\x18\b \x01(\tR\n" +
	"updateTime\x12\"\n" +
	"\fcategoryName\x18\t \x01(\tR\fcategoryName\"<\n" +
	"\x0fRecordsResponse\x12)\n" +
	"\arecords\x18\x01 \x03(\v2\x0f.dish.v1.RecordR\arecords\"\xa7\x02\n" +
	"\fDishResponse\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\"\n" +
	"\fcategoryName\x18\x02 \x01(\tR\fcategoryName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\aflavors\x18\x04 \x03(\v2\x0f.dish.v1.FlavorR\aflavors\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\x03R\x02id\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\b \x01(\x02R\x05price\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"updateTime\x18\n" +
	" \x01(\tR\n" +
	"updateTime\"?\n" +
	"\x0eDishesResponse\x12-\n" +
	"\x06dishes\x18\x01 \x03(\v2\x15.dish.v1.DishResponseR\x06dishes\"M\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x14\n" +
	"\x05curId\x18\x03 \x01(\x03R\x05curId2\xca\x04\n" +
	"\vDishService\x128\n" +
	"\x06Create\x12\x14.dish.v1.DishRequest\x1a\x16.dish.v1.EmptyResponse\"\x00\x128\n" +
	"\x06Update\x12\x14.dish.v1.DishRequest\x1a\x16.dish.v1.EmptyResponse\"\x00\x12;\n" +
	"\n" +
	"FindByPage\x12\x14.dish.v1.PageRequest\x1a\x15.dish.v1.PageResponse\"\x00\x12B\n" +
	"\x10FindByCategoryId\x12\x12.dish.v1.IDMessage\x1a\x18.dish.v1.RecordsResponse\"\x00\x127\n" +
	"\bFindById\x12\x12.dish.v1.IDMessage\x1a\x15.dish.v1.DishResponse\"\x00\x12@\n" +
	"\fUpdateStatus\x12\x16.dish.v1.UpdateRequest\x1a\x16.dish.v1.EmptyResponse\"\x00\x127\n" +
	"\x06Delete\x12\x13.dish.v1.IdsMessage\x1a\x16.dish.v1.EmptyResponse\"\x00\x12G\n" +
	"\x16FindByCategoryIdFlavor\x12\x12.dish.v1.IDMessage\x1a\x17.dish.v1.DishesResponse\"\x00\x12I\n" +
	"\x13FindDescriptionById\x12\x12.dish.v1.IDMessage\x1a\x1c.dish.v1.DescriptionResponse\"\x00BYZWgithub.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/dish-service/proto;dishpbb\x06proto3"

var (
	file_dish_proto_rawDescOnce sync.Once
	file_dish_proto_rawDescData []byte
)

func file_dish_proto_rawDescGZIP() []byte {
	file_dish_proto_rawDescOnce.Do(func() {
		file_dish_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dish_proto_rawDesc), len(file_dish_proto_rawDesc)))
	})
	return file_dish_proto_rawDescData
}

var file_dish_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dish_proto_goTypes = []any{
	(*EmptyResponse)(nil),       // 0: dish.v1.EmptyResponse
	(*IDMessage)(nil),           // 1: dish.v1.IDMessage
	(*DescriptionResponse)(nil), // 2: dish.v1.DescriptionResponse
	(*IdsMessage)(nil),          // 3: dish.v1.IdsMessage
	(*DishRequest)(nil),         // 4: dish.v1.DishRequest
	(*Flavor)(nil),              // 5: dish.v1.Flavor
	(*PageRequest)(nil),         // 6: dish.v1.PageRequest
	(*PageResponse)(nil),        // 7: dish.v1.PageResponse
	(*Record)(nil),              // 8: dish.v1.Record
	(*RecordsResponse)(nil),     // 9: dish.v1.RecordsResponse
	(*DishResponse)(nil),        // 10: dish.v1.DishResponse
	(*DishesResponse)(nil),      // 11: dish.v1.DishesResponse
	(*UpdateRequest)(nil),       // 12: dish.v1.UpdateRequest
}
var file_dish_proto_depIdxs = []int32{
	5,  // 0: dish.v1.DishRequest.flavors:type_name -> dish.v1.Flavor
	8,  // 1: dish.v1.PageResponse.records:type_name -> dish.v1.Record
	8,  // 2: dish.v1.RecordsResponse.records:type_name -> dish.v1.Record
	5,  // 3: dish.v1.DishResponse.flavors:type_name -> dish.v1.Flavor
	10, // 4: dish.v1.DishesResponse.dishes:type_name -> dish.v1.DishResponse
	4,  // 5: dish.v1.DishService.Create:input_type -> dish.v1.DishRequest
	4,  // 6: dish.v1.DishService.Update:input_type -> dish.v1.DishRequest
	6,  // 7: dish.v1.DishService.FindByPage:input_type -> dish.v1.PageRequest
	1,  // 8: dish.v1.DishService.FindByCategoryId:input_type -> dish.v1.IDMessage
	1,  // 9: dish.v1.DishService.FindById:input_type -> dish.v1.IDMessage
	12, // 10: dish.v1.DishService.UpdateStatus:input_type -> dish.v1.UpdateRequest
	3,  // 11: dish.v1.DishService.Delete:input_type -> dish.v1.IdsMessage
	1,  // 12: dish.v1.DishService.FindByCategoryIdFlavor:input_type -> dish.v1.IDMessage
	1,  // 13: dish.v1.DishService.FindDescriptionById:input_type -> dish.v1.IDMessage
	0,  // 14: dish.v1.DishService.Create:output_type -> dish.v1.EmptyResponse
	0,  // 15: dish.v1.DishService.Update:output_type -> dish.v1.EmptyResponse
	7,  // 16: dish.v1.DishService.FindByPage:output_type -> dish.v1.PageResponse
	9,  // 17: dish.v1.DishService.FindByCategoryId:output_type -> dish.v1.RecordsResponse
	10, // 18: dish.v1.DishService.FindById:output_type -> dish.v1.DishResponse
	0,  // 19: dish.v1.DishService.UpdateStatus:output_type -> dish.v1.EmptyResponse
	0,  // 20: dish.v1.DishService.Delete:output_type -> dish.v1.EmptyResponse
	11, // 21: dish.v1.DishService.FindByCategoryIdFlavor:output_type -> dish.v1.DishesResponse
	2,  // 22: dish.v1.DishService.FindDescriptionById:output_type -> dish.v1.DescriptionResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_dish_proto_init() }
func file_dish_proto_init() {
	if File_dish_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dish_proto_rawDesc), len(file_dish_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dish_proto_goTypes,
		DependencyIndexes: file_dish_proto_depIdxs,
		MessageInfos:      file_dish_proto_msgTypes,
	}.Build()
	File_dish_proto = out.File
	file_dish_proto_goTypes = nil
	file_dish_proto_depIdxs = nil
}
