// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initialize

import (
	application8 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/addressbook/application"
	infrastructure8 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/addressbook/infrastructure"
	interfaces9 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/addressbook/interfaces"
	application2 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/category/application"
	infrastructure2 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/category/infrastructure"
	interfaces2 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/category/interfaces"
	interfaces3 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/common/interfaces"
	application3 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/dish/application"
	infrastructure3 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/dish/infrastructure"
	interfaces4 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/dish/interfaces"
	"github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/employee/application"
	"github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/employee/infrastructure"
	"github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/employee/interfaces"
	application9 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/order/application"
	infrastructure9 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/order/infrastructure"
	interfaces10 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/order/interfaces"
	application4 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/setmeal/application"
	infrastructure4 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/setmeal/infrastructure"
	interfaces5 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/setmeal/interfaces"
	application5 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/shop/application"
	infrastructure5 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/shop/infrastructure"
	interfaces6 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/shop/interfaces"
	application7 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/shopping_cart/application"
	infrastructure7 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/shopping_cart/infrastructure"
	interfaces8 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/shopping_cart/interfaces"
	application6 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/user/application"
	infrastructure6 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/user/infrastructure"
	interfaces7 "github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/internal/user/interfaces"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func Init() (*gin.Engine, error) {
	db, err := NewMysqlDatabase()
	if err != nil {
		return nil, err
	}
	employeeRepository := infrastructure.NewDefaultEmployeeRepository(db)
	employeeService := application.NewEmployeeService(employeeRepository)
	employeeHandler := interfaces.NewEmployeeHandler(employeeService)
	categoryRepository := infrastructure2.NewDefaultCategoryRepository(db)
	categoryAppService := application2.NewCategoryService(categoryRepository)
	categoryHandler := interfaces2.NewCategoryHandler(categoryAppService)
	commonHandler := interfaces3.NewCommonHandler()
	defaultDishRepository := infrastructure3.NewDefaultDishRepository(db)
	client, err := NewRedisDatabase()
	if err != nil {
		return nil, err
	}
	dishRepository := infrastructure3.NewCachedDishRepository(defaultDishRepository, client)
	dishService := application3.NewDishService(dishRepository, categoryRepository)
	dishHandler := interfaces4.NewDishHandler(dishService)
	setMealRepository := infrastructure4.NewDefaultSetMealRepository(db)
	setMealService := application4.NewSetMealService(setMealRepository, categoryRepository, dishRepository)
	setMealHandler := interfaces5.NewSetMealHandler(setMealService)
	shopRepository := infrastructure5.NewDefaultShopRepository(client)
	shopService := application5.NewShopService(shopRepository)
	shopHandler := interfaces6.NewShopHandler(shopService)
	userRepository := infrastructure6.NewDefaultUserRepository(db)
	userService := application6.NewUserService(userRepository)
	userHandler := interfaces7.NewUserHandler(userService)
	shoppingCartRepository := infrastructure7.NewDefaultShoppingCartRepository(db)
	shoppingCartService := application7.NewShoppingCartService(shoppingCartRepository, dishRepository, setMealRepository)
	shoppingCartHandler := interfaces8.NewShoppingCartHandler(shoppingCartService)
	addressRepository := infrastructure8.NewDefaultAddressRepository(db)
	addressService := application8.NewAddressService(addressRepository)
	addressHandler := interfaces9.NewAddressHandler(addressService)
	orderRepository := infrastructure9.NewDefaultOrderRepository(db)
	orderService := application9.NewOrderService(orderRepository, shoppingCartRepository, addressRepository)
	orderHandler := interfaces10.NewOrderHandler(orderService)
	engine := NewRouter(employeeHandler, categoryHandler, commonHandler, dishHandler, setMealHandler, shopHandler, userHandler, shoppingCartHandler, addressHandler, orderHandler)
	return engine, nil
}

// wire.go:

type Application struct {
	Router *gin.Engine
}
