// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: dish.proto

package dishpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DishService_Create_FullMethodName                 = "/dish.v1.DishService/Create"
	DishService_Update_FullMethodName                 = "/dish.v1.DishService/Update"
	DishService_FindByPage_FullMethodName             = "/dish.v1.DishService/FindByPage"
	DishService_FindByCategoryId_FullMethodName       = "/dish.v1.DishService/FindByCategoryId"
	DishService_FindById_FullMethodName               = "/dish.v1.DishService/FindById"
	DishService_UpdateStatus_FullMethodName           = "/dish.v1.DishService/UpdateStatus"
	DishService_Delete_FullMethodName                 = "/dish.v1.DishService/Delete"
	DishService_FindByCategoryIdFlavor_FullMethodName = "/dish.v1.DishService/FindByCategoryIdFlavor"
)

// DishServiceClient is the client API for DishService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DishServiceClient interface {
	Create(ctx context.Context, in *DishRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Update(ctx context.Context, in *DishRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	FindByPage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error)
	FindByCategoryId(ctx context.Context, in *IDMessage, opts ...grpc.CallOption) (*RecordsResponse, error)
	FindById(ctx context.Context, in *IDMessage, opts ...grpc.CallOption) (*DishResponse, error)
	UpdateStatus(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Delete(ctx context.Context, in *IdsMessage, opts ...grpc.CallOption) (*EmptyResponse, error)
	FindByCategoryIdFlavor(ctx context.Context, in *IDMessage, opts ...grpc.CallOption) (*DishesResponse, error)
}

type dishServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDishServiceClient(cc grpc.ClientConnInterface) DishServiceClient {
	return &dishServiceClient{cc}
}

func (c *dishServiceClient) Create(ctx context.Context, in *DishRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, DishService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dishServiceClient) Update(ctx context.Context, in *DishRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, DishService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dishServiceClient) FindByPage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageResponse)
	err := c.cc.Invoke(ctx, DishService_FindByPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dishServiceClient) FindByCategoryId(ctx context.Context, in *IDMessage, opts ...grpc.CallOption) (*RecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordsResponse)
	err := c.cc.Invoke(ctx, DishService_FindByCategoryId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dishServiceClient) FindById(ctx context.Context, in *IDMessage, opts ...grpc.CallOption) (*DishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DishResponse)
	err := c.cc.Invoke(ctx, DishService_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dishServiceClient) UpdateStatus(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, DishService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dishServiceClient) Delete(ctx context.Context, in *IdsMessage, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, DishService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dishServiceClient) FindByCategoryIdFlavor(ctx context.Context, in *IDMessage, opts ...grpc.CallOption) (*DishesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DishesResponse)
	err := c.cc.Invoke(ctx, DishService_FindByCategoryIdFlavor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DishServiceServer is the server API for DishService service.
// All implementations must embed UnimplementedDishServiceServer
// for forward compatibility.
type DishServiceServer interface {
	Create(context.Context, *DishRequest) (*EmptyResponse, error)
	Update(context.Context, *DishRequest) (*EmptyResponse, error)
	FindByPage(context.Context, *PageRequest) (*PageResponse, error)
	FindByCategoryId(context.Context, *IDMessage) (*RecordsResponse, error)
	FindById(context.Context, *IDMessage) (*DishResponse, error)
	UpdateStatus(context.Context, *UpdateRequest) (*EmptyResponse, error)
	Delete(context.Context, *IdsMessage) (*EmptyResponse, error)
	FindByCategoryIdFlavor(context.Context, *IDMessage) (*DishesResponse, error)
	mustEmbedUnimplementedDishServiceServer()
}

// UnimplementedDishServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDishServiceServer struct{}

func (UnimplementedDishServiceServer) Create(context.Context, *DishRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDishServiceServer) Update(context.Context, *DishRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDishServiceServer) FindByPage(context.Context, *PageRequest) (*PageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByPage not implemented")
}
func (UnimplementedDishServiceServer) FindByCategoryId(context.Context, *IDMessage) (*RecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByCategoryId not implemented")
}
func (UnimplementedDishServiceServer) FindById(context.Context, *IDMessage) (*DishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedDishServiceServer) UpdateStatus(context.Context, *UpdateRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedDishServiceServer) Delete(context.Context, *IdsMessage) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDishServiceServer) FindByCategoryIdFlavor(context.Context, *IDMessage) (*DishesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByCategoryIdFlavor not implemented")
}
func (UnimplementedDishServiceServer) mustEmbedUnimplementedDishServiceServer() {}
func (UnimplementedDishServiceServer) testEmbeddedByValue()                     {}

// UnsafeDishServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interfaces is not recommended, as added methods to DishServiceServer will
// result in compilation errors.
type UnsafeDishServiceServer interface {
	mustEmbedUnimplementedDishServiceServer()
}

func RegisterDishServiceServer(s grpc.ServiceRegistrar, srv DishServiceServer) {
	// If the following call pancis, it indicates UnimplementedDishServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DishService_ServiceDesc, srv)
}

func _DishService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DishServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DishService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DishServiceServer).Create(ctx, req.(*DishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DishService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DishServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DishService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DishServiceServer).Update(ctx, req.(*DishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DishService_FindByPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DishServiceServer).FindByPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DishService_FindByPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DishServiceServer).FindByPage(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DishService_FindByCategoryId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DishServiceServer).FindByCategoryId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DishService_FindByCategoryId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DishServiceServer).FindByCategoryId(ctx, req.(*IDMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DishService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DishServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DishService_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DishServiceServer).FindById(ctx, req.(*IDMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DishService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DishServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DishService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DishServiceServer).UpdateStatus(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DishService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DishServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DishService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DishServiceServer).Delete(ctx, req.(*IdsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DishService_FindByCategoryIdFlavor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DishServiceServer).FindByCategoryIdFlavor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DishService_FindByCategoryIdFlavor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DishServiceServer).FindByCategoryIdFlavor(ctx, req.(*IDMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// DishService_ServiceDesc is the grpc.ServiceDesc for DishService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DishService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dish.v1.DishService",
	HandlerType: (*DishServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DishService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DishService_Update_Handler,
		},
		{
			MethodName: "FindByPage",
			Handler:    _DishService_FindByPage_Handler,
		},
		{
			MethodName: "FindByCategoryId",
			Handler:    _DishService_FindByCategoryId_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _DishService_FindById_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _DishService_UpdateStatus_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DishService_Delete_Handler,
		},
		{
			MethodName: "FindByCategoryIdFlavor",
			Handler:    _DishService_FindByCategoryIdFlavor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dish.proto",
}
