// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initialize

import (
	"github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/api-gateway/internal/interfaces/rest"
	"github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/api-gateway/internal/persistence/rpc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func Init() (*gin.Engine, error) {
	employeeServiceClient := rpc.NewEmployeeServiceClient()
	employeeService := rpc.NewEmployeeService(employeeServiceClient)
	employeeHandler := rest.NewEmployeeHandler(employeeService)
	categoryServiceClient := rpc.NewCategoryServiceClient()
	categoryService := rpc.NewCategoryService(categoryServiceClient)
	categoryHandler := rest.NewCategoryHandler(categoryService)
	dishServiceClient := rpc.NewDishServiceClient()
	dishService := rpc.NewDishService(dishServiceClient)
	dishHandler := rest.NewDishHandler(dishService)
	setmealServiceClient := rpc.NewSetmealServiceClient()
	setMealService := rpc.NewSetMealService(setmealServiceClient)
	setMealHandler := rest.NewSetMealHandler(setMealService)
	commonHandler := rest.NewCommonHandler()
	userServiceClient := rpc.NewUserServiceClient()
	userService := rpc.NewUserService(userServiceClient)
	userHandler := rest.NewUserHandler(userService)
	shopServiceClient := rpc.NewShopServiceClient()
	shopService := rpc.NewShopService(shopServiceClient)
	shopHandler := rest.NewShopHandler(shopService)
	shoppingCartServiceClient := rpc.NewShoppingCartServiceClient()
	shoppingCartService := rpc.NewShoppingCartService(shoppingCartServiceClient)
	shoppingCartHandler := rest.NewShoppingCartHandler(shoppingCartService)
	addressBookServiceClient := rpc.NewAddressBookServiceClient()
	addressService := rpc.NewAddressBookService(addressBookServiceClient)
	addressHandler := rest.NewAddressHandler(addressService)
	orderServiceClient := rpc.NewOrderServiceClient()
	orderService := rpc.NewOrderService(orderServiceClient)
	orderHandler := rest.NewOrderHandler(orderService)
	engine := NewRouter(employeeHandler, categoryHandler, dishHandler, setMealHandler, commonHandler, userHandler, shopHandler, shoppingCartHandler, addressHandler, orderHandler)
	return engine, nil
}

// wire.go:

type Application struct {
	Router *gin.Engine
}
