// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: addressbook.proto

package addressbookpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_addressbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_addressbook_proto_rawDescGZIP(), []int{0}
}

func (x *IdMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_addressbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_addressbook_proto_rawDescGZIP(), []int{1}
}

type AddressBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CityCode      string                 `protobuf:"bytes,1,opt,name=cityCode,proto3" json:"cityCode,omitempty"`
	CityName      string                 `protobuf:"bytes,2,opt,name=cityName,proto3" json:"cityName,omitempty"`
	Consignee     string                 `protobuf:"bytes,3,opt,name=consignee,proto3" json:"consignee,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	DistrictCode  string                 `protobuf:"bytes,5,opt,name=districtCode,proto3" json:"districtCode,omitempty"`
	DistrictName  string                 `protobuf:"bytes,6,opt,name=districtName,proto3" json:"districtName,omitempty"`
	Id            int64                  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	IsDefault     int32                  `protobuf:"varint,8,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	Label         int32                  `protobuf:"varint,9,opt,name=label,proto3" json:"label,omitempty"`
	Phone         string                 `protobuf:"bytes,10,opt,name=phone,proto3" json:"phone,omitempty"`
	ProvinceCode  string                 `protobuf:"bytes,11,opt,name=provinceCode,proto3" json:"provinceCode,omitempty"`
	ProvinceName  string                 `protobuf:"bytes,12,opt,name=provinceName,proto3" json:"provinceName,omitempty"`
	Sex           string                 `protobuf:"bytes,13,opt,name=sex,proto3" json:"sex,omitempty"`
	UserId        int64                  `protobuf:"varint,14,opt,name=userId,proto3" json:"userId,omitempty"`
	CurId         int64                  `protobuf:"varint,15,opt,name=curId,proto3" json:"curId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressBookRequest) Reset() {
	*x = AddressBookRequest{}
	mi := &file_addressbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBookRequest) ProtoMessage() {}

func (x *AddressBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBookRequest.ProtoReflect.Descriptor instead.
func (*AddressBookRequest) Descriptor() ([]byte, []int) {
	return file_addressbook_proto_rawDescGZIP(), []int{2}
}

func (x *AddressBookRequest) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *AddressBookRequest) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *AddressBookRequest) GetConsignee() string {
	if x != nil {
		return x.Consignee
	}
	return ""
}

func (x *AddressBookRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AddressBookRequest) GetDistrictCode() string {
	if x != nil {
		return x.DistrictCode
	}
	return ""
}

func (x *AddressBookRequest) GetDistrictName() string {
	if x != nil {
		return x.DistrictName
	}
	return ""
}

func (x *AddressBookRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressBookRequest) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *AddressBookRequest) GetLabel() int32 {
	if x != nil {
		return x.Label
	}
	return 0
}

func (x *AddressBookRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddressBookRequest) GetProvinceCode() string {
	if x != nil {
		return x.ProvinceCode
	}
	return ""
}

func (x *AddressBookRequest) GetProvinceName() string {
	if x != nil {
		return x.ProvinceName
	}
	return ""
}

func (x *AddressBookRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *AddressBookRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddressBookRequest) GetCurId() int64 {
	if x != nil {
		return x.CurId
	}
	return 0
}

type AddressBookListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressBooks  []*AddressBookResponse `protobuf:"bytes,1,rep,name=addressBooks,proto3" json:"addressBooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressBookListResponse) Reset() {
	*x = AddressBookListResponse{}
	mi := &file_addressbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressBookListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBookListResponse) ProtoMessage() {}

func (x *AddressBookListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBookListResponse.ProtoReflect.Descriptor instead.
func (*AddressBookListResponse) Descriptor() ([]byte, []int) {
	return file_addressbook_proto_rawDescGZIP(), []int{3}
}

func (x *AddressBookListResponse) GetAddressBooks() []*AddressBookResponse {
	if x != nil {
		return x.AddressBooks
	}
	return nil
}

type AddressBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Consignee     string                 `protobuf:"bytes,3,opt,name=consignee,proto3" json:"consignee,omitempty"`
	Sex           string                 `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	ProvinceCode  string                 `protobuf:"bytes,6,opt,name=provinceCode,proto3" json:"provinceCode,omitempty"`
	ProvinceName  string                 `protobuf:"bytes,7,opt,name=provinceName,proto3" json:"provinceName,omitempty"`
	CityCode      string                 `protobuf:"bytes,8,opt,name=cityCode,proto3" json:"cityCode,omitempty"`
	CityName      string                 `protobuf:"bytes,9,opt,name=cityName,proto3" json:"cityName,omitempty"`
	DistrictCode  string                 `protobuf:"bytes,10,opt,name=districtCode,proto3" json:"districtCode,omitempty"`
	DistrictName  string                 `protobuf:"bytes,11,opt,name=districtName,proto3" json:"districtName,omitempty"`
	Detail        string                 `protobuf:"bytes,12,opt,name=detail,proto3" json:"detail,omitempty"`
	Label         string                 `protobuf:"bytes,13,opt,name=label,proto3" json:"label,omitempty"`
	IsDefault     int32                  `protobuf:"varint,14,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressBookResponse) Reset() {
	*x = AddressBookResponse{}
	mi := &file_addressbook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBookResponse) ProtoMessage() {}

func (x *AddressBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBookResponse.ProtoReflect.Descriptor instead.
func (*AddressBookResponse) Descriptor() ([]byte, []int) {
	return file_addressbook_proto_rawDescGZIP(), []int{4}
}

func (x *AddressBookResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressBookResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddressBookResponse) GetConsignee() string {
	if x != nil {
		return x.Consignee
	}
	return ""
}

func (x *AddressBookResponse) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *AddressBookResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddressBookResponse) GetProvinceCode() string {
	if x != nil {
		return x.ProvinceCode
	}
	return ""
}

func (x *AddressBookResponse) GetProvinceName() string {
	if x != nil {
		return x.ProvinceName
	}
	return ""
}

func (x *AddressBookResponse) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *AddressBookResponse) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *AddressBookResponse) GetDistrictCode() string {
	if x != nil {
		return x.DistrictCode
	}
	return ""
}

func (x *AddressBookResponse) GetDistrictName() string {
	if x != nil {
		return x.DistrictName
	}
	return ""
}

func (x *AddressBookResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AddressBookResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AddressBookResponse) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

type UpdateDefaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDefaultRequest) Reset() {
	*x = UpdateDefaultRequest{}
	mi := &file_addressbook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefaultRequest) ProtoMessage() {}

func (x *UpdateDefaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefaultRequest.ProtoReflect.Descriptor instead.
func (*UpdateDefaultRequest) Descriptor() ([]byte, []int) {
	return file_addressbook_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDefaultRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDefaultRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_addressbook_proto protoreflect.FileDescriptor

const file_addressbook_proto_rawDesc = "" +
	"\n" +
	"\x11addressbook.proto\x12\x0eaddressbook.v1\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x0e\n" +
	"\fEmptyMessage\"\xac\x03\n" +
	"\x12AddressBookRequest\x12\x1a\n" +
	"\bcityCode\x18\x01 \x01(\tR\bcityCode\x12\x1a\n" +
	"\bcityName\x18\x02 \x01(\tR\bcityName\x12\x1c\n" +
	"\tconsignee\x18\x03 \x01(\tR\tconsignee\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\"\n" +
	"\fdistrictCode\x18\x05 \x01(\tR\fdistrictCode\x12\"\n" +
	"\fdistrictName\x18\x06 \x01(\tR\fdistrictName\x12\x0e\n" +
	"\x02id\x18\a \x01(\x03R\x02id\x12\x1c\n" +
	"\tisDefault\x18\b \x01(\x05R\tisDefault\x12\x14\n" +
	"\x05label\x18\t \x01(\x05R\x05label\x12\x14\n" +
	"\x05phone\x18\n" +
	" \x01(\tR\x05phone\x12\"\n" +
	"\fprovinceCode\x18\v \x01(\tR\fprovinceCode\x12\"\n" +
	"\fprovinceName\x18\f \x01(\tR\fprovinceName\x12\x10\n" +
	"\x03sex\x18\r \x01(\tR\x03sex\x12\x16\n" +
	"\x06userId\x18\x0e \x01(\x03R\x06userId\x12\x14\n" +
	"\x05curId\x18\x0f \x01(\x03R\x05curId\"b\n" +
	"\x17AddressBookListResponse\x12G\n" +
	"\faddressBooks\x18\x01 \x03(\v2#.addressbook.v1.AddressBookResponseR\faddressBooks\"\x97\x03\n" +
	"\x13AddressBookResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tconsignee\x18\x03 \x01(\tR\tconsignee\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\"\n" +
	"\fprovinceCode\x18\x06 \x01(\tR\fprovinceCode\x12\"\n" +
	"\fprovinceName\x18\a \x01(\tR\fprovinceName\x12\x1a\n" +
	"\bcityCode\x18\b \x01(\tR\bcityCode\x12\x1a\n" +
	"\bcityName\x18\t \x01(\tR\bcityName\x12\"\n" +
	"\fdistrictCode\x18\n" +
	" \x01(\tR\fdistrictCode\x12\"\n" +
	"\fdistrictName\x18\v \x01(\tR\fdistrictName\x12\x16\n" +
	"\x06detail\x18\f \x01(\tR\x06detail\x12\x14\n" +
	"\x05label\x18\r \x01(\tR\x05label\x12\x1c\n" +
	"\tisDefault\x18\x0e \x01(\x05R\tisDefault\">\n" +
	"\x14UpdateDefaultRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId2\xc5\x04\n" +
	"\x12AddressBookService\x12L\n" +
	"\x06Create\x12\".addressbook.v1.AddressBookRequest\x1a\x1c.addressbook.v1.EmptyMessage\"\x00\x12T\n" +
	"\fFindByUserId\x12\x19.addressbook.v1.IdMessage\x1a'.addressbook.v1.AddressBookListResponse\"\x00\x12O\n" +
	"\vFindDefault\x12\x19.addressbook.v1.IdMessage\x1a#.addressbook.v1.AddressBookResponse\"\x00\x12U\n" +
	"\rUpdateDefault\x12$.addressbook.v1.UpdateDefaultRequest\x1a\x1c.addressbook.v1.EmptyMessage\"\x00\x12L\n" +
	"\bFindById\x12\x19.addressbook.v1.IdMessage\x1a#.addressbook.v1.AddressBookResponse\"\x00\x12G\n" +
	"\n" +
	"DeleteById\x12\x19.addressbook.v1.IdMessage\x1a\x1c.addressbook.v1.EmptyMessage\"\x00\x12L\n" +
	"\x06Update\x12\".addressbook.v1.AddressBookRequest\x1a\x1c.addressbook.v1.EmptyMessage\"\x00BgZegithub.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/addressbook-service/proto;addressbookpbb\x06proto3"

var (
	file_addressbook_proto_rawDescOnce sync.Once
	file_addressbook_proto_rawDescData []byte
)

func file_addressbook_proto_rawDescGZIP() []byte {
	file_addressbook_proto_rawDescOnce.Do(func() {
		file_addressbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_addressbook_proto_rawDesc), len(file_addressbook_proto_rawDesc)))
	})
	return file_addressbook_proto_rawDescData
}

var file_addressbook_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_addressbook_proto_goTypes = []any{
	(*IdMessage)(nil),               // 0: addressbook.v1.IdMessage
	(*EmptyMessage)(nil),            // 1: addressbook.v1.EmptyMessage
	(*AddressBookRequest)(nil),      // 2: addressbook.v1.AddressBookRequest
	(*AddressBookListResponse)(nil), // 3: addressbook.v1.AddressBookListResponse
	(*AddressBookResponse)(nil),     // 4: addressbook.v1.AddressBookResponse
	(*UpdateDefaultRequest)(nil),    // 5: addressbook.v1.UpdateDefaultRequest
}
var file_addressbook_proto_depIdxs = []int32{
	4, // 0: addressbook.v1.AddressBookListResponse.addressBooks:type_name -> addressbook.v1.AddressBookResponse
	2, // 1: addressbook.v1.AddressBookService.Create:input_type -> addressbook.v1.AddressBookRequest
	0, // 2: addressbook.v1.AddressBookService.FindByUserId:input_type -> addressbook.v1.IdMessage
	0, // 3: addressbook.v1.AddressBookService.FindDefault:input_type -> addressbook.v1.IdMessage
	5, // 4: addressbook.v1.AddressBookService.UpdateDefault:input_type -> addressbook.v1.UpdateDefaultRequest
	0, // 5: addressbook.v1.AddressBookService.FindById:input_type -> addressbook.v1.IdMessage
	0, // 6: addressbook.v1.AddressBookService.DeleteById:input_type -> addressbook.v1.IdMessage
	2, // 7: addressbook.v1.AddressBookService.Update:input_type -> addressbook.v1.AddressBookRequest
	1, // 8: addressbook.v1.AddressBookService.Create:output_type -> addressbook.v1.EmptyMessage
	3, // 9: addressbook.v1.AddressBookService.FindByUserId:output_type -> addressbook.v1.AddressBookListResponse
	4, // 10: addressbook.v1.AddressBookService.FindDefault:output_type -> addressbook.v1.AddressBookResponse
	1, // 11: addressbook.v1.AddressBookService.UpdateDefault:output_type -> addressbook.v1.EmptyMessage
	4, // 12: addressbook.v1.AddressBookService.FindById:output_type -> addressbook.v1.AddressBookResponse
	1, // 13: addressbook.v1.AddressBookService.DeleteById:output_type -> addressbook.v1.EmptyMessage
	1, // 14: addressbook.v1.AddressBookService.Update:output_type -> addressbook.v1.EmptyMessage
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_addressbook_proto_init() }
func file_addressbook_proto_init() {
	if File_addressbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_addressbook_proto_rawDesc), len(file_addressbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_addressbook_proto_goTypes,
		DependencyIndexes: file_addressbook_proto_depIdxs,
		MessageInfos:      file_addressbook_proto_msgTypes,
	}.Build()
	File_addressbook_proto = out.File
	file_addressbook_proto_goTypes = nil
	file_addressbook_proto_depIdxs = nil
}
