// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: addressbook.proto

package addressbookpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AddressBookService_Create_FullMethodName        = "/addressbook.v1.AddressBookService/Create"
	AddressBookService_FindByUserId_FullMethodName  = "/addressbook.v1.AddressBookService/FindByUserId"
	AddressBookService_FindDefault_FullMethodName   = "/addressbook.v1.AddressBookService/FindDefault"
	AddressBookService_UpdateDefault_FullMethodName = "/addressbook.v1.AddressBookService/UpdateDefault"
	AddressBookService_FindById_FullMethodName      = "/addressbook.v1.AddressBookService/FindById"
	AddressBookService_DeleteById_FullMethodName    = "/addressbook.v1.AddressBookService/DeleteById"
	AddressBookService_Update_FullMethodName        = "/addressbook.v1.AddressBookService/Update"
)

// AddressBookServiceClient is the client API for AddressBookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddressBookServiceClient interface {
	Create(ctx context.Context, in *AddressBookRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	FindByUserId(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*AddressBookListResponse, error)
	FindDefault(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*AddressBookResponse, error)
	UpdateDefault(ctx context.Context, in *UpdateDefaultRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	FindById(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*AddressBookResponse, error)
	DeleteById(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
	Update(ctx context.Context, in *AddressBookRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type addressBookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressBookServiceClient(cc grpc.ClientConnInterface) AddressBookServiceClient {
	return &addressBookServiceClient{cc}
}

func (c *addressBookServiceClient) Create(ctx context.Context, in *AddressBookRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, AddressBookService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookServiceClient) FindByUserId(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*AddressBookListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressBookListResponse)
	err := c.cc.Invoke(ctx, AddressBookService_FindByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookServiceClient) FindDefault(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*AddressBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressBookResponse)
	err := c.cc.Invoke(ctx, AddressBookService_FindDefault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookServiceClient) UpdateDefault(ctx context.Context, in *UpdateDefaultRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, AddressBookService_UpdateDefault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookServiceClient) FindById(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*AddressBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressBookResponse)
	err := c.cc.Invoke(ctx, AddressBookService_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookServiceClient) DeleteById(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, AddressBookService_DeleteById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookServiceClient) Update(ctx context.Context, in *AddressBookRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, AddressBookService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressBookServiceServer is the server API for AddressBookService service.
// All implementations must embed UnimplementedAddressBookServiceServer
// for forward compatibility.
type AddressBookServiceServer interface {
	Create(context.Context, *AddressBookRequest) (*EmptyMessage, error)
	FindByUserId(context.Context, *IdMessage) (*AddressBookListResponse, error)
	FindDefault(context.Context, *IdMessage) (*AddressBookResponse, error)
	UpdateDefault(context.Context, *UpdateDefaultRequest) (*EmptyMessage, error)
	FindById(context.Context, *IdMessage) (*AddressBookResponse, error)
	DeleteById(context.Context, *IdMessage) (*EmptyMessage, error)
	Update(context.Context, *AddressBookRequest) (*EmptyMessage, error)
	mustEmbedUnimplementedAddressBookServiceServer()
}

// UnimplementedAddressBookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddressBookServiceServer struct{}

func (UnimplementedAddressBookServiceServer) Create(context.Context, *AddressBookRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAddressBookServiceServer) FindByUserId(context.Context, *IdMessage) (*AddressBookListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByUserId not implemented")
}
func (UnimplementedAddressBookServiceServer) FindDefault(context.Context, *IdMessage) (*AddressBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDefault not implemented")
}
func (UnimplementedAddressBookServiceServer) UpdateDefault(context.Context, *UpdateDefaultRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDefault not implemented")
}
func (UnimplementedAddressBookServiceServer) FindById(context.Context, *IdMessage) (*AddressBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedAddressBookServiceServer) DeleteById(context.Context, *IdMessage) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteById not implemented")
}
func (UnimplementedAddressBookServiceServer) Update(context.Context, *AddressBookRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAddressBookServiceServer) mustEmbedUnimplementedAddressBookServiceServer() {}
func (UnimplementedAddressBookServiceServer) testEmbeddedByValue()                            {}

// UnsafeAddressBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddressBookServiceServer will
// result in compilation errors.
type UnsafeAddressBookServiceServer interface {
	mustEmbedUnimplementedAddressBookServiceServer()
}

func RegisterAddressBookServiceServer(s grpc.ServiceRegistrar, srv AddressBookServiceServer) {
	// If the following call pancis, it indicates UnimplementedAddressBookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AddressBookService_ServiceDesc, srv)
}

func _AddressBookService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressBookService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).Create(ctx, req.(*AddressBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBookService_FindByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).FindByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressBookService_FindByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).FindByUserId(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBookService_FindDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).FindDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressBookService_FindDefault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).FindDefault(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBookService_UpdateDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).UpdateDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressBookService_UpdateDefault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).UpdateDefault(ctx, req.(*UpdateDefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBookService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressBookService_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).FindById(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBookService_DeleteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).DeleteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressBookService_DeleteById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).DeleteById(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBookService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddressBookService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).Update(ctx, req.(*AddressBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddressBookService_ServiceDesc is the grpc.ServiceDesc for AddressBookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddressBookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "addressbook.v1.AddressBookService",
	HandlerType: (*AddressBookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AddressBookService_Create_Handler,
		},
		{
			MethodName: "FindByUserId",
			Handler:    _AddressBookService_FindByUserId_Handler,
		},
		{
			MethodName: "FindDefault",
			Handler:    _AddressBookService_FindDefault_Handler,
		},
		{
			MethodName: "UpdateDefault",
			Handler:    _AddressBookService_UpdateDefault_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _AddressBookService_FindById_Handler,
		},
		{
			MethodName: "DeleteById",
			Handler:    _AddressBookService_DeleteById_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AddressBookService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addressbook.proto",
}
