// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: setmeal.proto

package setmealpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_setmeal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{0}
}

func (x *IdMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IdsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdsMessage) Reset() {
	*x = IdsMessage{}
	mi := &file_setmeal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdsMessage) ProtoMessage() {}

func (x *IdsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdsMessage.ProtoReflect.Descriptor instead.
func (*IdsMessage) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{1}
}

func (x *IdsMessage) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_setmeal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{2}
}

type SetMealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	SetMealDishes []*SetMealDish         `protobuf:"bytes,7,rep,name=setMealDishes,proto3" json:"setMealDishes,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CurId         int64                  `protobuf:"varint,9,opt,name=curId,proto3" json:"curId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMealRequest) Reset() {
	*x = SetMealRequest{}
	mi := &file_setmeal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMealRequest) ProtoMessage() {}

func (x *SetMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMealRequest.ProtoReflect.Descriptor instead.
func (*SetMealRequest) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{3}
}

func (x *SetMealRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SetMealRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SetMealRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetMealRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SetMealRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetMealRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SetMealRequest) GetSetMealDishes() []*SetMealDish {
	if x != nil {
		return x.SetMealDishes
	}
	return nil
}

func (x *SetMealRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SetMealRequest) GetCurId() int64 {
	if x != nil {
		return x.CurId
	}
	return 0
}

type SetMealDish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Copies        int32                  `protobuf:"varint,1,opt,name=copies,proto3" json:"copies,omitempty"`
	DishId        int64                  `protobuf:"varint,2,opt,name=dishId,proto3" json:"dishId,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	SetmealId     int64                  `protobuf:"varint,6,opt,name=setmealId,proto3" json:"setmealId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMealDish) Reset() {
	*x = SetMealDish{}
	mi := &file_setmeal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMealDish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMealDish) ProtoMessage() {}

func (x *SetMealDish) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMealDish.ProtoReflect.Descriptor instead.
func (*SetMealDish) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{4}
}

func (x *SetMealDish) GetCopies() int32 {
	if x != nil {
		return x.Copies
	}
	return 0
}

func (x *SetMealDish) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *SetMealDish) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetMealDish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetMealDish) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SetMealDish) GetSetmealId() int64 {
	if x != nil {
		return x.SetmealId
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurId         int64                  `protobuf:"varint,2,opt,name=curId,proto3" json:"curId,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_setmeal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{5}
}

func (x *StatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatusRequest) GetCurId() int64 {
	if x != nil {
		return x.CurId
	}
	return 0
}

func (x *StatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type SetMealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	SetMealDishes []*SetMealDish         `protobuf:"bytes,7,rep,name=setMealDishes,proto3" json:"setMealDishes,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CategoryName  string                 `protobuf:"bytes,9,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,10,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMealResponse) Reset() {
	*x = SetMealResponse{}
	mi := &file_setmeal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMealResponse) ProtoMessage() {}

func (x *SetMealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMealResponse.ProtoReflect.Descriptor instead.
func (*SetMealResponse) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{6}
}

func (x *SetMealResponse) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SetMealResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SetMealResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetMealResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SetMealResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetMealResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SetMealResponse) GetSetMealDishes() []*SetMealDish {
	if x != nil {
		return x.SetMealDishes
	}
	return nil
}

func (x *SetMealResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SetMealResponse) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *SetMealResponse) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_setmeal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{7}
}

func (x *PageRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *PageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*Record              `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_setmeal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{8}
}

func (x *PageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,8,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	CategoryName  string                 `protobuf:"bytes,9,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_setmeal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{9}
}

func (x *Record) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Record) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Record) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Record) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Record) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Record) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *Record) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type FindDishByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*DishMessage         `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindDishByIdResponse) Reset() {
	*x = FindDishByIdResponse{}
	mi := &file_setmeal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindDishByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDishByIdResponse) ProtoMessage() {}

func (x *FindDishByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDishByIdResponse.ProtoReflect.Descriptor instead.
func (*FindDishByIdResponse) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{10}
}

func (x *FindDishByIdResponse) GetDishes() []*DishMessage {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type DishMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Copies        int32                  `protobuf:"varint,1,opt,name=copies,proto3" json:"copies,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishMessage) Reset() {
	*x = DishMessage{}
	mi := &file_setmeal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishMessage) ProtoMessage() {}

func (x *DishMessage) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishMessage.ProtoReflect.Descriptor instead.
func (*DishMessage) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{11}
}

func (x *DishMessage) GetCopies() int32 {
	if x != nil {
		return x.Copies
	}
	return 0
}

func (x *DishMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DishMessage) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DishMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FindByCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setmeals      []*SetMealMessage      `protobuf:"bytes,1,rep,name=setmeals,proto3" json:"setmeals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByCategoryResponse) Reset() {
	*x = FindByCategoryResponse{}
	mi := &file_setmeal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByCategoryResponse) ProtoMessage() {}

func (x *FindByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByCategoryResponse.ProtoReflect.Descriptor instead.
func (*FindByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{12}
}

func (x *FindByCategoryResponse) GetSetmeals() []*SetMealMessage {
	if x != nil {
		return x.Setmeals
	}
	return nil
}

type SetMealMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	CreateTime    string                 `protobuf:"bytes,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	CreateUser    int64                  `protobuf:"varint,3,opt,name=createUser,proto3" json:"createUser,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Id            int64                  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,10,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	UpdateUser    int64                  `protobuf:"varint,11,opt,name=updateUser,proto3" json:"updateUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMealMessage) Reset() {
	*x = SetMealMessage{}
	mi := &file_setmeal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMealMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMealMessage) ProtoMessage() {}

func (x *SetMealMessage) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMealMessage.ProtoReflect.Descriptor instead.
func (*SetMealMessage) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{13}
}

func (x *SetMealMessage) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SetMealMessage) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *SetMealMessage) GetCreateUser() int64 {
	if x != nil {
		return x.CreateUser
	}
	return 0
}

func (x *SetMealMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SetMealMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetMealMessage) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SetMealMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetMealMessage) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SetMealMessage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SetMealMessage) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *SetMealMessage) GetUpdateUser() int64 {
	if x != nil {
		return x.UpdateUser
	}
	return 0
}

type ShoppingCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingCartResponse) Reset() {
	*x = ShoppingCartResponse{}
	mi := &file_setmeal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingCartResponse) ProtoMessage() {}

func (x *ShoppingCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setmeal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingCartResponse.ProtoReflect.Descriptor instead.
func (*ShoppingCartResponse) Descriptor() ([]byte, []int) {
	return file_setmeal_proto_rawDescGZIP(), []int{14}
}

func (x *ShoppingCartResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShoppingCartResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ShoppingCartResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_setmeal_proto protoreflect.FileDescriptor

const file_setmeal_proto_rawDesc = "" +
	"\n" +
	"\rsetmeal.proto\x12\n" +
	"setmeal.v1\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1e\n" +
	"\n" +
	"IdsMessage\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"\x0e\n" +
	"\fEmptyRequest\"\x8f\x02\n" +
	"\x0eSetMealRequest\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x03R\n" +
	"categoryId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x02R\x05price\x12=\n" +
	"\rsetMealDishes\x18\a \x03(\v2\x17.setmeal.v1.SetMealDishR\rsetMealDishes\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x14\n" +
	"\x05curId\x18\t \x01(\x03R\x05curId\"\x95\x01\n" +
	"\vSetMealDish\x12\x16\n" +
	"\x06copies\x18\x01 \x01(\x05R\x06copies\x12\x16\n" +
	"\x06dishId\x18\x02 \x01(\x03R\x06dishId\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12\x1c\n" +
	"\tsetmealId\x18\x06 \x01(\x03R\tsetmealId\"M\n" +
	"\rStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05curId\x18\x02 \x01(\x03R\x05curId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\xbe\x02\n" +
	"\x0fSetMealResponse\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x03R\n" +
	"categoryId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x02R\x05price\x12=\n" +
	"\rsetMealDishes\x18\a \x03(\v2\x17.setmeal.v1.SetMealDishR\rsetMealDishes\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\"\n" +
	"\fcategoryName\x18\t \x01(\tR\fcategoryName\x12\x1e\n" +
	"\n" +
	"updateTime\x18\n" +
	" \x01(\tR\n" +
	"updateTime\"\x89\x01\n" +
	"\vPageRequest\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"R\n" +
	"\fPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12,\n" +
	"\arecords\x18\x02 \x03(\v2\x12.setmeal.v1.RecordR\arecords\"\xf6\x01\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\x12\x1e\n" +
	"\n" +
	"updateTime\x18\b \x01(\tR\n" +
	"updateTime\x12\"\n" +
	"\fcategoryName\x18\t \x01(\tR\fcategoryName\"G\n" +
	"\x14FindDishByIdResponse\x12/\n" +
	"\x06dishes\x18\x01 \x03(\v2\x17.setmeal.v1.DishMessageR\x06dishes\"q\n" +
	"\vDishMessage\x12\x16\n" +
	"\x06copies\x18\x01 \x01(\x05R\x06copies\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"P\n" +
	"\x16FindByCategoryResponse\x126\n" +
	"\bsetmeals\x18\x01 \x03(\v2\x1a.setmeal.v1.SetMealMessageR\bsetmeals\"\xba\x02\n" +
	"\x0eSetMealMessage\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x02 \x01(\tR\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"createUser\x18\x03 \x01(\x03R\n" +
	"createUser\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\x03R\x02id\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\b \x01(\x02R\x05price\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"updateTime\x18\n" +
	" \x01(\tR\n" +
	"updateTime\x12\x1e\n" +
	"\n" +
	"updateUser\x18\v \x01(\x03R\n" +
	"updateUser\"V\n" +
	"\x14ShoppingCartResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price2\x86\x05\n" +
	"\x0eSetmealService\x12@\n" +
	"\x06Create\x12\x1a.setmeal.v1.SetMealRequest\x1a\x18.setmeal.v1.EmptyRequest\"\x00\x12=\n" +
	"\aDeletes\x12\x16.setmeal.v1.IdsMessage\x1a\x18.setmeal.v1.EmptyRequest\"\x00\x12@\n" +
	"\x06Update\x12\x1a.setmeal.v1.SetMealRequest\x1a\x18.setmeal.v1.EmptyRequest\"\x00\x12E\n" +
	"\fUpdateStatus\x12\x19.setmeal.v1.StatusRequest\x1a\x18.setmeal.v1.EmptyRequest\"\x00\x12@\n" +
	"\bFindById\x12\x15.setmeal.v1.IdMessage\x1a\x1b.setmeal.v1.SetMealResponse\"\x00\x12?\n" +
	"\bFindPage\x12\x17.setmeal.v1.PageRequest\x1a\x18.setmeal.v1.PageResponse\"\x00\x12O\n" +
	"\x10FindByCategoryId\x12\x15.setmeal.v1.IdMessage\x1a\".setmeal.v1.FindByCategoryResponse\"\x00\x12I\n" +
	"\fFindDishById\x12\x15.setmeal.v1.IdMessage\x1a .setmeal.v1.FindDishByIdResponse\"\x00\x12K\n" +
	"\x0eFindDetailById\x12\x15.setmeal.v1.IdMessage\x1a .setmeal.v1.ShoppingCartResponse\"\x00B_Z]github.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/setmeal-service/proto;setmealpbb\x06proto3"

var (
	file_setmeal_proto_rawDescOnce sync.Once
	file_setmeal_proto_rawDescData []byte
)

func file_setmeal_proto_rawDescGZIP() []byte {
	file_setmeal_proto_rawDescOnce.Do(func() {
		file_setmeal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_setmeal_proto_rawDesc), len(file_setmeal_proto_rawDesc)))
	})
	return file_setmeal_proto_rawDescData
}

var file_setmeal_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_setmeal_proto_goTypes = []any{
	(*IdMessage)(nil),              // 0: setmeal.v1.IdMessage
	(*IdsMessage)(nil),             // 1: setmeal.v1.IdsMessage
	(*EmptyRequest)(nil),           // 2: setmeal.v1.EmptyRequest
	(*SetMealRequest)(nil),         // 3: setmeal.v1.SetMealRequest
	(*SetMealDish)(nil),            // 4: setmeal.v1.SetMealDish
	(*StatusRequest)(nil),          // 5: setmeal.v1.StatusRequest
	(*SetMealResponse)(nil),        // 6: setmeal.v1.SetMealResponse
	(*PageRequest)(nil),            // 7: setmeal.v1.PageRequest
	(*PageResponse)(nil),           // 8: setmeal.v1.PageResponse
	(*Record)(nil),                 // 9: setmeal.v1.Record
	(*FindDishByIdResponse)(nil),   // 10: setmeal.v1.FindDishByIdResponse
	(*DishMessage)(nil),            // 11: setmeal.v1.DishMessage
	(*FindByCategoryResponse)(nil), // 12: setmeal.v1.FindByCategoryResponse
	(*SetMealMessage)(nil),         // 13: setmeal.v1.SetMealMessage
	(*ShoppingCartResponse)(nil),   // 14: setmeal.v1.ShoppingCartResponse
}
var file_setmeal_proto_depIdxs = []int32{
	4,  // 0: setmeal.v1.SetMealRequest.setMealDishes:type_name -> setmeal.v1.SetMealDish
	4,  // 1: setmeal.v1.SetMealResponse.setMealDishes:type_name -> setmeal.v1.SetMealDish
	9,  // 2: setmeal.v1.PageResponse.records:type_name -> setmeal.v1.Record
	11, // 3: setmeal.v1.FindDishByIdResponse.dishes:type_name -> setmeal.v1.DishMessage
	13, // 4: setmeal.v1.FindByCategoryResponse.setmeals:type_name -> setmeal.v1.SetMealMessage
	3,  // 5: setmeal.v1.SetmealService.Create:input_type -> setmeal.v1.SetMealRequest
	1,  // 6: setmeal.v1.SetmealService.Deletes:input_type -> setmeal.v1.IdsMessage
	3,  // 7: setmeal.v1.SetmealService.Update:input_type -> setmeal.v1.SetMealRequest
	5,  // 8: setmeal.v1.SetmealService.UpdateStatus:input_type -> setmeal.v1.StatusRequest
	0,  // 9: setmeal.v1.SetmealService.FindById:input_type -> setmeal.v1.IdMessage
	7,  // 10: setmeal.v1.SetmealService.FindPage:input_type -> setmeal.v1.PageRequest
	0,  // 11: setmeal.v1.SetmealService.FindByCategoryId:input_type -> setmeal.v1.IdMessage
	0,  // 12: setmeal.v1.SetmealService.FindDishById:input_type -> setmeal.v1.IdMessage
	0,  // 13: setmeal.v1.SetmealService.FindDetailById:input_type -> setmeal.v1.IdMessage
	2,  // 14: setmeal.v1.SetmealService.Create:output_type -> setmeal.v1.EmptyRequest
	2,  // 15: setmeal.v1.SetmealService.Deletes:output_type -> setmeal.v1.EmptyRequest
	2,  // 16: setmeal.v1.SetmealService.Update:output_type -> setmeal.v1.EmptyRequest
	2,  // 17: setmeal.v1.SetmealService.UpdateStatus:output_type -> setmeal.v1.EmptyRequest
	6,  // 18: setmeal.v1.SetmealService.FindById:output_type -> setmeal.v1.SetMealResponse
	8,  // 19: setmeal.v1.SetmealService.FindPage:output_type -> setmeal.v1.PageResponse
	12, // 20: setmeal.v1.SetmealService.FindByCategoryId:output_type -> setmeal.v1.FindByCategoryResponse
	10, // 21: setmeal.v1.SetmealService.FindDishById:output_type -> setmeal.v1.FindDishByIdResponse
	14, // 22: setmeal.v1.SetmealService.FindDetailById:output_type -> setmeal.v1.ShoppingCartResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_setmeal_proto_init() }
func file_setmeal_proto_init() {
	if File_setmeal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_setmeal_proto_rawDesc), len(file_setmeal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_setmeal_proto_goTypes,
		DependencyIndexes: file_setmeal_proto_depIdxs,
		MessageInfos:      file_setmeal_proto_msgTypes,
	}.Build()
	File_setmeal_proto = out.File
	file_setmeal_proto_goTypes = nil
	file_setmeal_proto_depIdxs = nil
}
