// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shoppingcart.proto

package shoppingcartpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DishFlavor    string                 `protobuf:"bytes,1,opt,name=dishFlavor,proto3" json:"dishFlavor,omitempty"`
	DishId        int64                  `protobuf:"varint,2,opt,name=dishId,proto3" json:"dishId,omitempty"`
	SetMealId     int64                  `protobuf:"varint,3,opt,name=setMealId,proto3" json:"setMealId,omitempty"`
	CurId         int64                  `protobuf:"varint,4,opt,name=curId,proto3" json:"curId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartRequest) Reset() {
	*x = CartRequest{}
	mi := &file_shoppingcart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartRequest) ProtoMessage() {}

func (x *CartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingcart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartRequest.ProtoReflect.Descriptor instead.
func (*CartRequest) Descriptor() ([]byte, []int) {
	return file_shoppingcart_proto_rawDescGZIP(), []int{0}
}

func (x *CartRequest) GetDishFlavor() string {
	if x != nil {
		return x.DishFlavor
	}
	return ""
}

func (x *CartRequest) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *CartRequest) GetSetMealId() int64 {
	if x != nil {
		return x.SetMealId
	}
	return 0
}

func (x *CartRequest) GetCurId() int64 {
	if x != nil {
		return x.CurId
	}
	return 0
}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_shoppingcart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingcart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_shoppingcart_proto_rawDescGZIP(), []int{1}
}

func (x *IdMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_shoppingcart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingcart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_shoppingcart_proto_rawDescGZIP(), []int{2}
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*CartMessage         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_shoppingcart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingcart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_shoppingcart_proto_rawDescGZIP(), []int{3}
}

func (x *CartResponse) GetRecords() []*CartMessage {
	if x != nil {
		return x.Records
	}
	return nil
}

type CartMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	CreateTime    string                 `protobuf:"bytes,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	DishFlavor    string                 `protobuf:"bytes,3,opt,name=dishFlavor,proto3" json:"dishFlavor,omitempty"`
	DishId        int64                  `protobuf:"varint,4,opt,name=dishId,proto3" json:"dishId,omitempty"`
	Id            int64                  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Number        int32                  `protobuf:"varint,8,opt,name=number,proto3" json:"number,omitempty"`
	SetMealId     int64                  `protobuf:"varint,9,opt,name=setMealId,proto3" json:"setMealId,omitempty"`
	UserID        int64                  `protobuf:"varint,10,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartMessage) Reset() {
	*x = CartMessage{}
	mi := &file_shoppingcart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartMessage) ProtoMessage() {}

func (x *CartMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingcart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartMessage.ProtoReflect.Descriptor instead.
func (*CartMessage) Descriptor() ([]byte, []int) {
	return file_shoppingcart_proto_rawDescGZIP(), []int{4}
}

func (x *CartMessage) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CartMessage) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *CartMessage) GetDishFlavor() string {
	if x != nil {
		return x.DishFlavor
	}
	return ""
}

func (x *CartMessage) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *CartMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartMessage) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CartMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartMessage) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *CartMessage) GetSetMealId() int64 {
	if x != nil {
		return x.SetMealId
	}
	return 0
}

func (x *CartMessage) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

var File_shoppingcart_proto protoreflect.FileDescriptor

const file_shoppingcart_proto_rawDesc = "" +
	"\n" +
	"\x12shoppingcart.proto\x12\x0fshoppingcart.v1\"y\n" +
	"\vCartRequest\x12\x1e\n" +
	"\n" +
	"dishFlavor\x18\x01 \x01(\tR\n" +
	"dishFlavor\x12\x16\n" +
	"\x06dishId\x18\x02 \x01(\x03R\x06dishId\x12\x1c\n" +
	"\tsetMealId\x18\x03 \x01(\x03R\tsetMealId\x12\x14\n" +
	"\x05curId\x18\x04 \x01(\x03R\x05curId\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x0e\n" +
	"\fEmptyMessage\"F\n" +
	"\fCartResponse\x126\n" +
	"\arecords\x18\x01 \x03(\v2\x1c.shoppingcart.v1.CartMessageR\arecords\"\x85\x02\n" +
	"\vCartMessage\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x02R\x06amount\x12\x1e\n" +
	"\n" +
	"createTime\x18\x02 \x01(\tR\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"dishFlavor\x18\x03 \x01(\tR\n" +
	"dishFlavor\x12\x16\n" +
	"\x06dishId\x18\x04 \x01(\x03R\x06dishId\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\x03R\x02id\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\b \x01(\x05R\x06number\x12\x1c\n" +
	"\tsetMealId\x18\t \x01(\x03R\tsetMealId\x12\x16\n" +
	"\x06userID\x18\n" +
	" \x01(\x03R\x06userID2\xb5\x02\n" +
	"\x13ShoppingCartService\x12D\n" +
	"\x03Add\x12\x1c.shoppingcart.v1.CartRequest\x1a\x1d.shoppingcart.v1.EmptyMessage\"\x00\x12K\n" +
	"\fFindByUserId\x12\x1a.shoppingcart.v1.IdMessage\x1a\x1d.shoppingcart.v1.CartResponse\"\x00\x12D\n" +
	"\x03Sub\x12\x1c.shoppingcart.v1.CartRequest\x1a\x1d.shoppingcart.v1.EmptyMessage\"\x00\x12E\n" +
	"\x06Delete\x12\x1a.shoppingcart.v1.IdMessage\x1a\x1d.shoppingcart.v1.EmptyMessage\"\x00BiZggithub.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/shoppingcart-service/proto;shoppingcartpbb\x06proto3"

var (
	file_shoppingcart_proto_rawDescOnce sync.Once
	file_shoppingcart_proto_rawDescData []byte
)

func file_shoppingcart_proto_rawDescGZIP() []byte {
	file_shoppingcart_proto_rawDescOnce.Do(func() {
		file_shoppingcart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shoppingcart_proto_rawDesc), len(file_shoppingcart_proto_rawDesc)))
	})
	return file_shoppingcart_proto_rawDescData
}

var file_shoppingcart_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shoppingcart_proto_goTypes = []any{
	(*CartRequest)(nil),  // 0: shoppingcart.v1.CartRequest
	(*IdMessage)(nil),    // 1: shoppingcart.v1.IdMessage
	(*EmptyMessage)(nil), // 2: shoppingcart.v1.EmptyMessage
	(*CartResponse)(nil), // 3: shoppingcart.v1.CartResponse
	(*CartMessage)(nil),  // 4: shoppingcart.v1.CartMessage
}
var file_shoppingcart_proto_depIdxs = []int32{
	4, // 0: shoppingcart.v1.CartResponse.records:type_name -> shoppingcart.v1.CartMessage
	0, // 1: shoppingcart.v1.ShoppingCartService.Add:input_type -> shoppingcart.v1.CartRequest
	1, // 2: shoppingcart.v1.ShoppingCartService.FindByUserId:input_type -> shoppingcart.v1.IdMessage
	0, // 3: shoppingcart.v1.ShoppingCartService.Sub:input_type -> shoppingcart.v1.CartRequest
	1, // 4: shoppingcart.v1.ShoppingCartService.Delete:input_type -> shoppingcart.v1.IdMessage
	2, // 5: shoppingcart.v1.ShoppingCartService.Add:output_type -> shoppingcart.v1.EmptyMessage
	3, // 6: shoppingcart.v1.ShoppingCartService.FindByUserId:output_type -> shoppingcart.v1.CartResponse
	2, // 7: shoppingcart.v1.ShoppingCartService.Sub:output_type -> shoppingcart.v1.EmptyMessage
	2, // 8: shoppingcart.v1.ShoppingCartService.Delete:output_type -> shoppingcart.v1.EmptyMessage
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shoppingcart_proto_init() }
func file_shoppingcart_proto_init() {
	if File_shoppingcart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shoppingcart_proto_rawDesc), len(file_shoppingcart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shoppingcart_proto_goTypes,
		DependencyIndexes: file_shoppingcart_proto_depIdxs,
		MessageInfos:      file_shoppingcart_proto_msgTypes,
	}.Build()
	File_shoppingcart_proto = out.File
	file_shoppingcart_proto_goTypes = nil
	file_shoppingcart_proto_depIdxs = nil
}
