// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *IdMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

type CreateSameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	CurId         int64                  `protobuf:"varint,2,opt,name=curId,proto3" json:"curId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSameRequest) Reset() {
	*x = CreateSameRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSameRequest) ProtoMessage() {}

func (x *CreateSameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSameRequest.ProtoReflect.Descriptor instead.
func (*CreateSameRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSameRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateSameRequest) GetCurId() int64 {
	if x != nil {
		return x.CurId
	}
	return 0
}

type SubmitRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AddressBookId         int64                  `protobuf:"varint,1,opt,name=addressBookId,proto3" json:"addressBookId,omitempty"`
	Amount                float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	DeliveryStatus        int32                  `protobuf:"varint,3,opt,name=deliveryStatus,proto3" json:"deliveryStatus,omitempty"`
	EstimatedDeliveryTime string                 `protobuf:"bytes,4,opt,name=estimatedDeliveryTime,proto3" json:"estimatedDeliveryTime,omitempty"`
	PackAmount            int32                  `protobuf:"varint,5,opt,name=packAmount,proto3" json:"packAmount,omitempty"`
	PayMethod             int32                  `protobuf:"varint,6,opt,name=payMethod,proto3" json:"payMethod,omitempty"`
	Remark                string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	TablewareNumber       int32                  `protobuf:"varint,8,opt,name=tablewareNumber,proto3" json:"tablewareNumber,omitempty"`
	TablewareStatus       int32                  `protobuf:"varint,9,opt,name=tablewareStatus,proto3" json:"tablewareStatus,omitempty"`
	CurId                 int64                  `protobuf:"varint,10,opt,name=curId,proto3" json:"curId,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitRequest) GetAddressBookId() int64 {
	if x != nil {
		return x.AddressBookId
	}
	return 0
}

func (x *SubmitRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SubmitRequest) GetDeliveryStatus() int32 {
	if x != nil {
		return x.DeliveryStatus
	}
	return 0
}

func (x *SubmitRequest) GetEstimatedDeliveryTime() string {
	if x != nil {
		return x.EstimatedDeliveryTime
	}
	return ""
}

func (x *SubmitRequest) GetPackAmount() int32 {
	if x != nil {
		return x.PackAmount
	}
	return 0
}

func (x *SubmitRequest) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

func (x *SubmitRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *SubmitRequest) GetTablewareNumber() int32 {
	if x != nil {
		return x.TablewareNumber
	}
	return 0
}

func (x *SubmitRequest) GetTablewareStatus() int32 {
	if x != nil {
		return x.TablewareStatus
	}
	return 0
}

func (x *SubmitRequest) GetCurId() int64 {
	if x != nil {
		return x.CurId
	}
	return 0
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderAmount   float64                `protobuf:"fixed64,2,opt,name=orderAmount,proto3" json:"orderAmount,omitempty"`
	OrderNumber   string                 `protobuf:"bytes,3,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	OrderTime     string                 `protobuf:"bytes,4,opt,name=orderTime,proto3" json:"orderTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubmitResponse) GetOrderAmount() float64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *SubmitResponse) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *SubmitResponse) GetOrderTime() string {
	if x != nil {
		return x.OrderTime
	}
	return ""
}

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber   string                 `protobuf:"bytes,1,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	PayMethod     int32                  `protobuf:"varint,2,opt,name=payMethod,proto3" json:"payMethod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentRequest) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *PaymentRequest) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

type PaymentResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EstimatedDeliveryTime string                 `protobuf:"bytes,1,opt,name=estimatedDeliveryTime,proto3" json:"estimatedDeliveryTime,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentResponse) GetEstimatedDeliveryTime() string {
	if x != nil {
		return x.EstimatedDeliveryTime
	}
	return ""
}

type UserPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	CurId         int64                  `protobuf:"varint,4,opt,name=curId,proto3" json:"curId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPageRequest) Reset() {
	*x = UserPageRequest{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPageRequest) ProtoMessage() {}

func (x *UserPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPageRequest.ProtoReflect.Descriptor instead.
func (*UserPageRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *UserPageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserPageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserPageRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserPageRequest) GetCurId() int64 {
	if x != nil {
		return x.CurId
	}
	return 0
}

type UserPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*UserOrderResponse   `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPageResponse) Reset() {
	*x = UserPageResponse{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPageResponse) ProtoMessage() {}

func (x *UserPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPageResponse.ProtoReflect.Descriptor instead.
func (*UserPageResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *UserPageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserPageResponse) GetRecords() []*UserOrderResponse {
	if x != nil {
		return x.Records
	}
	return nil
}

type AdminPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*AdminOrderResponse  `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPageResponse) Reset() {
	*x = AdminPageResponse{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPageResponse) ProtoMessage() {}

func (x *AdminPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPageResponse.ProtoReflect.Descriptor instead.
func (*AdminPageResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *AdminPageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AdminPageResponse) GetRecords() []*AdminOrderResponse {
	if x != nil {
		return x.Records
	}
	return nil
}

type UserOrderResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number                string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Status                int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	UserId                int64                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	AddressBookId         int64                  `protobuf:"varint,5,opt,name=addressBookId,proto3" json:"addressBookId,omitempty"`
	OrderTime             string                 `protobuf:"bytes,6,opt,name=orderTime,proto3" json:"orderTime,omitempty"`
	CheckoutTime          string                 `protobuf:"bytes,7,opt,name=checkoutTime,proto3" json:"checkoutTime,omitempty"`
	PayMethod             int32                  `protobuf:"varint,8,opt,name=payMethod,proto3" json:"payMethod,omitempty"`
	PayStatus             int32                  `protobuf:"varint,9,opt,name=payStatus,proto3" json:"payStatus,omitempty"`
	Amount                float64                `protobuf:"fixed64,10,opt,name=amount,proto3" json:"amount,omitempty"`
	Remark                string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	Phone                 string                 `protobuf:"bytes,12,opt,name=phone,proto3" json:"phone,omitempty"`
	Address               string                 `protobuf:"bytes,13,opt,name=address,proto3" json:"address,omitempty"`
	UserName              string                 `protobuf:"bytes,14,opt,name=userName,proto3" json:"userName,omitempty"`
	Consignee             string                 `protobuf:"bytes,15,opt,name=consignee,proto3" json:"consignee,omitempty"`
	CancelReason          string                 `protobuf:"bytes,16,opt,name=cancelReason,proto3" json:"cancelReason,omitempty"`
	RejectionReason       string                 `protobuf:"bytes,17,opt,name=rejectionReason,proto3" json:"rejectionReason,omitempty"`
	CancelTime            string                 `protobuf:"bytes,18,opt,name=cancelTime,proto3" json:"cancelTime,omitempty"`
	EstimatedDeliveryTime string                 `protobuf:"bytes,19,opt,name=estimatedDeliveryTime,proto3" json:"estimatedDeliveryTime,omitempty"`
	DeliveryStatus        int32                  `protobuf:"varint,20,opt,name=deliveryStatus,proto3" json:"deliveryStatus,omitempty"`
	DeliveryTime          string                 `protobuf:"bytes,21,opt,name=deliveryTime,proto3" json:"deliveryTime,omitempty"`
	PackAmount            int32                  `protobuf:"varint,22,opt,name=packAmount,proto3" json:"packAmount,omitempty"`
	TableWareNumber       int32                  `protobuf:"varint,23,opt,name=tableWareNumber,proto3" json:"tableWareNumber,omitempty"`
	TableWareStatus       int32                  `protobuf:"varint,24,opt,name=tableWareStatus,proto3" json:"tableWareStatus,omitempty"`
	OrderDetails          []*OrderDetail         `protobuf:"bytes,25,rep,name=orderDetails,proto3" json:"orderDetails,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserOrderResponse) Reset() {
	*x = UserOrderResponse{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderResponse) ProtoMessage() {}

func (x *UserOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderResponse.ProtoReflect.Descriptor instead.
func (*UserOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *UserOrderResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserOrderResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *UserOrderResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserOrderResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserOrderResponse) GetAddressBookId() int64 {
	if x != nil {
		return x.AddressBookId
	}
	return 0
}

func (x *UserOrderResponse) GetOrderTime() string {
	if x != nil {
		return x.OrderTime
	}
	return ""
}

func (x *UserOrderResponse) GetCheckoutTime() string {
	if x != nil {
		return x.CheckoutTime
	}
	return ""
}

func (x *UserOrderResponse) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

func (x *UserOrderResponse) GetPayStatus() int32 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *UserOrderResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UserOrderResponse) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UserOrderResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserOrderResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserOrderResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserOrderResponse) GetConsignee() string {
	if x != nil {
		return x.Consignee
	}
	return ""
}

func (x *UserOrderResponse) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *UserOrderResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *UserOrderResponse) GetCancelTime() string {
	if x != nil {
		return x.CancelTime
	}
	return ""
}

func (x *UserOrderResponse) GetEstimatedDeliveryTime() string {
	if x != nil {
		return x.EstimatedDeliveryTime
	}
	return ""
}

func (x *UserOrderResponse) GetDeliveryStatus() int32 {
	if x != nil {
		return x.DeliveryStatus
	}
	return 0
}

func (x *UserOrderResponse) GetDeliveryTime() string {
	if x != nil {
		return x.DeliveryTime
	}
	return ""
}

func (x *UserOrderResponse) GetPackAmount() int32 {
	if x != nil {
		return x.PackAmount
	}
	return 0
}

func (x *UserOrderResponse) GetTableWareNumber() int32 {
	if x != nil {
		return x.TableWareNumber
	}
	return 0
}

func (x *UserOrderResponse) GetTableWareStatus() int32 {
	if x != nil {
		return x.TableWareStatus
	}
	return 0
}

func (x *UserOrderResponse) GetOrderDetails() []*OrderDetail {
	if x != nil {
		return x.OrderDetails
	}
	return nil
}

type OrderDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	DishFlavor    string                 `protobuf:"bytes,2,opt,name=dishFlavor,proto3" json:"dishFlavor,omitempty"`
	DishId        int64                  `protobuf:"varint,3,opt,name=dishId,proto3" json:"dishId,omitempty"`
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Number        int32                  `protobuf:"varint,7,opt,name=number,proto3" json:"number,omitempty"`
	OrderId       int64                  `protobuf:"varint,8,opt,name=orderId,proto3" json:"orderId,omitempty"`
	SetMealId     int64                  `protobuf:"varint,9,opt,name=setMealId,proto3" json:"setMealId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *OrderDetail) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderDetail) GetDishFlavor() string {
	if x != nil {
		return x.DishFlavor
	}
	return ""
}

func (x *OrderDetail) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *OrderDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderDetail) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *OrderDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderDetail) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *OrderDetail) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderDetail) GetSetMealId() int64 {
	if x != nil {
		return x.SetMealId
	}
	return 0
}

type AdminOrderResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number                string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Status                int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	UserId                int64                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	AddressBookId         int64                  `protobuf:"varint,5,opt,name=addressBookId,proto3" json:"addressBookId,omitempty"`
	OrderTime             string                 `protobuf:"bytes,6,opt,name=orderTime,proto3" json:"orderTime,omitempty"`
	CheckoutTime          string                 `protobuf:"bytes,7,opt,name=checkoutTime,proto3" json:"checkoutTime,omitempty"`
	PayMethod             int32                  `protobuf:"varint,8,opt,name=payMethod,proto3" json:"payMethod,omitempty"`
	PayStatus             int32                  `protobuf:"varint,9,opt,name=payStatus,proto3" json:"payStatus,omitempty"`
	Amount                float64                `protobuf:"fixed64,10,opt,name=amount,proto3" json:"amount,omitempty"`
	Remark                string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	Phone                 string                 `protobuf:"bytes,12,opt,name=phone,proto3" json:"phone,omitempty"`
	Address               string                 `protobuf:"bytes,13,opt,name=address,proto3" json:"address,omitempty"`
	UserName              string                 `protobuf:"bytes,14,opt,name=userName,proto3" json:"userName,omitempty"`
	Consignee             string                 `protobuf:"bytes,15,opt,name=consignee,proto3" json:"consignee,omitempty"`
	CancelReason          string                 `protobuf:"bytes,16,opt,name=cancelReason,proto3" json:"cancelReason,omitempty"`
	RejectionReason       string                 `protobuf:"bytes,17,opt,name=rejectionReason,proto3" json:"rejectionReason,omitempty"`
	CancelTime            string                 `protobuf:"bytes,18,opt,name=cancelTime,proto3" json:"cancelTime,omitempty"`
	EstimatedDeliveryTime string                 `protobuf:"bytes,19,opt,name=estimatedDeliveryTime,proto3" json:"estimatedDeliveryTime,omitempty"`
	DeliveryStatus        int32                  `protobuf:"varint,20,opt,name=deliveryStatus,proto3" json:"deliveryStatus,omitempty"`
	DeliveryTime          string                 `protobuf:"bytes,21,opt,name=deliveryTime,proto3" json:"deliveryTime,omitempty"`
	PackAmount            int32                  `protobuf:"varint,22,opt,name=packAmount,proto3" json:"packAmount,omitempty"`
	TableWareNumber       int32                  `protobuf:"varint,23,opt,name=tableWareNumber,proto3" json:"tableWareNumber,omitempty"`
	TableWareStatus       int32                  `protobuf:"varint,24,opt,name=tableWareStatus,proto3" json:"tableWareStatus,omitempty"`
	OrderDishes           string                 `protobuf:"bytes,25,opt,name=orderDishes,proto3" json:"orderDishes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AdminOrderResponse) Reset() {
	*x = AdminOrderResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminOrderResponse) ProtoMessage() {}

func (x *AdminOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminOrderResponse.ProtoReflect.Descriptor instead.
func (*AdminOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *AdminOrderResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminOrderResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *AdminOrderResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminOrderResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminOrderResponse) GetAddressBookId() int64 {
	if x != nil {
		return x.AddressBookId
	}
	return 0
}

func (x *AdminOrderResponse) GetOrderTime() string {
	if x != nil {
		return x.OrderTime
	}
	return ""
}

func (x *AdminOrderResponse) GetCheckoutTime() string {
	if x != nil {
		return x.CheckoutTime
	}
	return ""
}

func (x *AdminOrderResponse) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

func (x *AdminOrderResponse) GetPayStatus() int32 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *AdminOrderResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AdminOrderResponse) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AdminOrderResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AdminOrderResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AdminOrderResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AdminOrderResponse) GetConsignee() string {
	if x != nil {
		return x.Consignee
	}
	return ""
}

func (x *AdminOrderResponse) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *AdminOrderResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *AdminOrderResponse) GetCancelTime() string {
	if x != nil {
		return x.CancelTime
	}
	return ""
}

func (x *AdminOrderResponse) GetEstimatedDeliveryTime() string {
	if x != nil {
		return x.EstimatedDeliveryTime
	}
	return ""
}

func (x *AdminOrderResponse) GetDeliveryStatus() int32 {
	if x != nil {
		return x.DeliveryStatus
	}
	return 0
}

func (x *AdminOrderResponse) GetDeliveryTime() string {
	if x != nil {
		return x.DeliveryTime
	}
	return ""
}

func (x *AdminOrderResponse) GetPackAmount() int32 {
	if x != nil {
		return x.PackAmount
	}
	return 0
}

func (x *AdminOrderResponse) GetTableWareNumber() int32 {
	if x != nil {
		return x.TableWareNumber
	}
	return 0
}

func (x *AdminOrderResponse) GetTableWareStatus() int32 {
	if x != nil {
		return x.TableWareStatus
	}
	return 0
}

func (x *AdminOrderResponse) GetOrderDishes() string {
	if x != nil {
		return x.OrderDishes
	}
	return ""
}

type AdminPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BeginTime     string                 `protobuf:"bytes,1,opt,name=beginTime,proto3" json:"beginTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Number        string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPageRequest) Reset() {
	*x = AdminPageRequest{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPageRequest) ProtoMessage() {}

func (x *AdminPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPageRequest.ProtoReflect.Descriptor instead.
func (*AdminPageRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *AdminPageRequest) GetBeginTime() string {
	if x != nil {
		return x.BeginTime
	}
	return ""
}

func (x *AdminPageRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *AdminPageRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *AdminPageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminPageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminPageRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AdminPageRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RejectionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RejectionReason string                 `protobuf:"bytes,1,opt,name=rejectionReason,proto3" json:"rejectionReason,omitempty"`
	Id              int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RejectionRequest) Reset() {
	*x = RejectionRequest{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectionRequest) ProtoMessage() {}

func (x *RejectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectionRequest.ProtoReflect.Descriptor instead.
func (*RejectionRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *RejectionRequest) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *RejectionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CancelReason  string                 `protobuf:"bytes,1,opt,name=cancelReason,proto3" json:"cancelReason,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *CancelRequest) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *CancelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StatisticsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Confirmed          int64                  `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	DeliveryInProgress int64                  `protobuf:"varint,2,opt,name=deliveryInProgress,proto3" json:"deliveryInProgress,omitempty"`
	ToBeConfirmed      int64                  `protobuf:"varint,3,opt,name=ToBeConfirmed,proto3" json:"ToBeConfirmed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatisticsResponse) Reset() {
	*x = StatisticsResponse{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResponse) ProtoMessage() {}

func (x *StatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsResponse.ProtoReflect.Descriptor instead.
func (*StatisticsResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *StatisticsResponse) GetConfirmed() int64 {
	if x != nil {
		return x.Confirmed
	}
	return 0
}

func (x *StatisticsResponse) GetDeliveryInProgress() int64 {
	if x != nil {
		return x.DeliveryInProgress
	}
	return 0
}

func (x *StatisticsResponse) GetToBeConfirmed() int64 {
	if x != nil {
		return x.ToBeConfirmed
	}
	return 0
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\border.v1\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x0e\n" +
	"\fEmptyMessage\"C\n" +
	"\x11CreateSameRequest\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\x12\x14\n" +
	"\x05curId\x18\x02 \x01(\x03R\x05curId\"\xeb\x02\n" +
	"\rSubmitRequest\x12$\n" +
	"\raddressBookId\x18\x01 \x01(\x03R\raddressBookId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12&\n" +
	"\x0edeliveryStatus\x18\x03 \x01(\x05R\x0edeliveryStatus\x124\n" +
	"\x15estimatedDeliveryTime\x18\x04 \x01(\tR\x15estimatedDeliveryTime\x12\x1e\n" +
	"\n" +
	"packAmount\x18\x05 \x01(\x05R\n" +
	"packAmount\x12\x1c\n" +
	"\tpayMethod\x18\x06 \x01(\x05R\tpayMethod\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x12(\n" +
	"\x0ftablewareNumber\x18\b \x01(\x05R\x0ftablewareNumber\x12(\n" +
	"\x0ftablewareStatus\x18\t \x01(\x05R\x0ftablewareStatus\x12\x14\n" +
	"\x05curId\x18\n" +
	" \x01(\x03R\x05curId\"\x82\x01\n" +
	"\x0eSubmitResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vorderAmount\x18\x02 \x01(\x01R\vorderAmount\x12 \n" +
	"\vorderNumber\x18\x03 \x01(\tR\vorderNumber\x12\x1c\n" +
	"\torderTime\x18\x04 \x01(\tR\torderTime\"P\n" +
	"\x0ePaymentRequest\x12 \n" +
	"\vorderNumber\x18\x01 \x01(\tR\vorderNumber\x12\x1c\n" +
	"\tpayMethod\x18\x02 \x01(\x05R\tpayMethod\"G\n" +
	"\x0fPaymentResponse\x124\n" +
	"\x15estimatedDeliveryTime\x18\x01 \x01(\tR\x15estimatedDeliveryTime\"o\n" +
	"\x0fUserPageRequest\x12\x1a\n" +
	"\bpageSize\x18\x01 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x14\n" +
	"\x05curId\x18\x04 \x01(\x03R\x05curId\"_\n" +
	"\x10UserPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x125\n" +
	"\arecords\x18\x02 \x03(\v2\x1b.order.v1.UserOrderResponseR\arecords\"a\n" +
	"\x11AdminPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x126\n" +
	"\arecords\x18\x02 \x03(\v2\x1c.order.v1.AdminOrderResponseR\arecords\"\xc8\x06\n" +
	"\x11UserOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x03R\x06userId\x12$\n" +
	"\raddressBookId\x18\x05 \x01(\x03R\raddressBookId\x12\x1c\n" +
	"\torderTime\x18\x06 \x01(\tR\torderTime\x12\"\n" +
	"\fcheckoutTime\x18\a \x01(\tR\fcheckoutTime\x12\x1c\n" +
	"\tpayMethod\x18\b \x01(\x05R\tpayMethod\x12\x1c\n" +
	"\tpayStatus\x18\t \x01(\x05R\tpayStatus\x12\x16\n" +
	"\x06amount\x18\n" +
	" \x01(\x01R\x06amount\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12\x14\n" +
	"\x05phone\x18\f \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\r \x01(\tR\aaddress\x12\x1a\n" +
	"\buserName\x18\x0e \x01(\tR\buserName\x12\x1c\n" +
	"\tconsignee\x18\x0f \x01(\tR\tconsignee\x12\"\n" +
	"\fcancelReason\x18\x10 \x01(\tR\fcancelReason\x12(\n" +
	"\x0frejectionReason\x18\x11 \x01(\tR\x0frejectionReason\x12\x1e\n" +
	"\n" +
	"cancelTime\x18\x12 \x01(\tR\n" +
	"cancelTime\x124\n" +
	"\x15estimatedDeliveryTime\x18\x13 \x01(\tR\x15estimatedDeliveryTime\x12&\n" +
	"\x0edeliveryStatus\x18\x14 \x01(\x05R\x0edeliveryStatus\x12\"\n" +
	"\fdeliveryTime\x18\x15 \x01(\tR\fdeliveryTime\x12\x1e\n" +
	"\n" +
	"packAmount\x18\x16 \x01(\x05R\n" +
	"packAmount\x12(\n" +
	"\x0ftableWareNumber\x18\x17 \x01(\x05R\x0ftableWareNumber\x12(\n" +
	"\x0ftableWareStatus\x18\x18 \x01(\x05R\x0ftableWareStatus\x129\n" +
	"\forderDetails\x18\x19 \x03(\v2\x15.order.v1.OrderDetailR\forderDetails\"\xe7\x01\n" +
	"\vOrderDetail\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1e\n" +
	"\n" +
	"dishFlavor\x18\x02 \x01(\tR\n" +
	"dishFlavor\x12\x16\n" +
	"\x06dishId\x18\x03 \x01(\x03R\x06dishId\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\a \x01(\x05R\x06number\x12\x18\n" +
	"\aorderId\x18\b \x01(\x03R\aorderId\x12\x1c\n" +
	"\tsetMealId\x18\t \x01(\x03R\tsetMealId\"\xb0\x06\n" +
	"\x12AdminOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x03R\x06userId\x12$\n" +
	"\raddressBookId\x18\x05 \x01(\x03R\raddressBookId\x12\x1c\n" +
	"\torderTime\x18\x06 \x01(\tR\torderTime\x12\"\n" +
	"\fcheckoutTime\x18\a \x01(\tR\fcheckoutTime\x12\x1c\n" +
	"\tpayMethod\x18\b \x01(\x05R\tpayMethod\x12\x1c\n" +
	"\tpayStatus\x18\t \x01(\x05R\tpayStatus\x12\x16\n" +
	"\x06amount\x18\n" +
	" \x01(\x01R\x06amount\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12\x14\n" +
	"\x05phone\x18\f \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\r \x01(\tR\aaddress\x12\x1a\n" +
	"\buserName\x18\x0e \x01(\tR\buserName\x12\x1c\n" +
	"\tconsignee\x18\x0f \x01(\tR\tconsignee\x12\"\n" +
	"\fcancelReason\x18\x10 \x01(\tR\fcancelReason\x12(\n" +
	"\x0frejectionReason\x18\x11 \x01(\tR\x0frejectionReason\x12\x1e\n" +
	"\n" +
	"cancelTime\x18\x12 \x01(\tR\n" +
	"cancelTime\x124\n" +
	"\x15estimatedDeliveryTime\x18\x13 \x01(\tR\x15estimatedDeliveryTime\x12&\n" +
	"\x0edeliveryStatus\x18\x14 \x01(\x05R\x0edeliveryStatus\x12\"\n" +
	"\fdeliveryTime\x18\x15 \x01(\tR\fdeliveryTime\x12\x1e\n" +
	"\n" +
	"packAmount\x18\x16 \x01(\x05R\n" +
	"packAmount\x12(\n" +
	"\x0ftableWareNumber\x18\x17 \x01(\x05R\x0ftableWareNumber\x12(\n" +
	"\x0ftableWareStatus\x18\x18 \x01(\x05R\x0ftableWareStatus\x12 \n" +
	"\vorderDishes\x18\x19 \x01(\tR\vorderDishes\"\xc0\x01\n" +
	"\x10AdminPageRequest\x12\x1c\n" +
	"\tbeginTime\x18\x01 \x01(\tR\tbeginTime\x12\x18\n" +
	"\aendTime\x18\x02 \x01(\tR\aendTime\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"L\n" +
	"\x10RejectionRequest\x12(\n" +
	"\x0frejectionReason\x18\x01 \x01(\tR\x0frejectionReason\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"C\n" +
	"\rCancelRequest\x12\"\n" +
	"\fcancelReason\x18\x01 \x01(\tR\fcancelReason\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\x88\x01\n" +
	"\x12StatisticsResponse\x12\x1c\n" +
	"\tconfirmed\x18\x01 \x01(\x03R\tconfirmed\x12.\n" +
	"\x12deliveryInProgress\x18\x02 \x01(\x03R\x12deliveryInProgress\x12$\n" +
	"\rToBeConfirmed\x18\x03 \x01(\x03R\rToBeConfirmed2\xd8\x06\n" +
	"\fOrderService\x12=\n" +
	"\x06Submit\x12\x17.order.v1.SubmitRequest\x1a\x18.order.v1.SubmitResponse\"\x00\x12@\n" +
	"\aPayment\x12\x18.order.v1.PaymentRequest\x1a\x19.order.v1.PaymentResponse\"\x00\x12@\n" +
	"\x04Page\x12\x19.order.v1.UserPageRequest\x1a\x1b.order.v1.UserOrderResponse\"\x00\x12J\n" +
	"\rFindPageAdmin\x12\x1a.order.v1.AdminPageRequest\x1a\x1b.order.v1.AdminPageResponse\"\x00\x12>\n" +
	"\bGetOrder\x12\x13.order.v1.IdMessage\x1a\x1b.order.v1.UserOrderResponse\"\x00\x12;\n" +
	"\n" +
	"UserCancel\x12\x13.order.v1.IdMessage\x1a\x16.order.v1.EmptyMessage\"\x00\x12C\n" +
	"\n" +
	"CreateSame\x12\x1b.order.v1.CreateSameRequest\x1a\x16.order.v1.EmptyMessage\"\x00\x128\n" +
	"\aConfirm\x12\x13.order.v1.IdMessage\x1a\x16.order.v1.EmptyMessage\"\x00\x12A\n" +
	"\tRejection\x12\x1a.order.v1.RejectionRequest\x1a\x16.order.v1.EmptyMessage\"\x00\x12;\n" +
	"\x06Cancel\x12\x17.order.v1.CancelRequest\x1a\x16.order.v1.EmptyMessage\"\x00\x129\n" +
	"\bDelivery\x12\x13.order.v1.IdMessage\x1a\x16.order.v1.EmptyMessage\"\x00\x129\n" +
	"\bComplete\x12\x13.order.v1.IdMessage\x1a\x16.order.v1.EmptyMessage\"\x00\x12G\n" +
	"\rGetStatistics\x12\x16.order.v1.EmptyMessage\x1a\x1c.order.v1.StatisticsResponse\"\x00B[ZYgithub.com/Wafer233/WaferTakeOut/Server/wafer-take-out-server/order-service/proto;orderpbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_order_proto_goTypes = []any{
	(*IdMessage)(nil),          // 0: order.v1.IdMessage
	(*EmptyMessage)(nil),       // 1: order.v1.EmptyMessage
	(*CreateSameRequest)(nil),  // 2: order.v1.CreateSameRequest
	(*SubmitRequest)(nil),      // 3: order.v1.SubmitRequest
	(*SubmitResponse)(nil),     // 4: order.v1.SubmitResponse
	(*PaymentRequest)(nil),     // 5: order.v1.PaymentRequest
	(*PaymentResponse)(nil),    // 6: order.v1.PaymentResponse
	(*UserPageRequest)(nil),    // 7: order.v1.UserPageRequest
	(*UserPageResponse)(nil),   // 8: order.v1.UserPageResponse
	(*AdminPageResponse)(nil),  // 9: order.v1.AdminPageResponse
	(*UserOrderResponse)(nil),  // 10: order.v1.UserOrderResponse
	(*OrderDetail)(nil),        // 11: order.v1.OrderDetail
	(*AdminOrderResponse)(nil), // 12: order.v1.AdminOrderResponse
	(*AdminPageRequest)(nil),   // 13: order.v1.AdminPageRequest
	(*RejectionRequest)(nil),   // 14: order.v1.RejectionRequest
	(*CancelRequest)(nil),      // 15: order.v1.CancelRequest
	(*StatisticsResponse)(nil), // 16: order.v1.StatisticsResponse
}
var file_order_proto_depIdxs = []int32{
	10, // 0: order.v1.UserPageResponse.records:type_name -> order.v1.UserOrderResponse
	12, // 1: order.v1.AdminPageResponse.records:type_name -> order.v1.AdminOrderResponse
	11, // 2: order.v1.UserOrderResponse.orderDetails:type_name -> order.v1.OrderDetail
	3,  // 3: order.v1.OrderService.Submit:input_type -> order.v1.SubmitRequest
	5,  // 4: order.v1.OrderService.Payment:input_type -> order.v1.PaymentRequest
	7,  // 5: order.v1.OrderService.Page:input_type -> order.v1.UserPageRequest
	13, // 6: order.v1.OrderService.FindPageAdmin:input_type -> order.v1.AdminPageRequest
	0,  // 7: order.v1.OrderService.GetOrder:input_type -> order.v1.IdMessage
	0,  // 8: order.v1.OrderService.UserCancel:input_type -> order.v1.IdMessage
	2,  // 9: order.v1.OrderService.CreateSame:input_type -> order.v1.CreateSameRequest
	0,  // 10: order.v1.OrderService.Confirm:input_type -> order.v1.IdMessage
	14, // 11: order.v1.OrderService.Rejection:input_type -> order.v1.RejectionRequest
	15, // 12: order.v1.OrderService.Cancel:input_type -> order.v1.CancelRequest
	0,  // 13: order.v1.OrderService.Delivery:input_type -> order.v1.IdMessage
	0,  // 14: order.v1.OrderService.Complete:input_type -> order.v1.IdMessage
	1,  // 15: order.v1.OrderService.GetStatistics:input_type -> order.v1.EmptyMessage
	4,  // 16: order.v1.OrderService.Submit:output_type -> order.v1.SubmitResponse
	6,  // 17: order.v1.OrderService.Payment:output_type -> order.v1.PaymentResponse
	10, // 18: order.v1.OrderService.Page:output_type -> order.v1.UserOrderResponse
	9,  // 19: order.v1.OrderService.FindPageAdmin:output_type -> order.v1.AdminPageResponse
	10, // 20: order.v1.OrderService.GetOrder:output_type -> order.v1.UserOrderResponse
	1,  // 21: order.v1.OrderService.UserCancel:output_type -> order.v1.EmptyMessage
	1,  // 22: order.v1.OrderService.CreateSame:output_type -> order.v1.EmptyMessage
	1,  // 23: order.v1.OrderService.Confirm:output_type -> order.v1.EmptyMessage
	1,  // 24: order.v1.OrderService.Rejection:output_type -> order.v1.EmptyMessage
	1,  // 25: order.v1.OrderService.Cancel:output_type -> order.v1.EmptyMessage
	1,  // 26: order.v1.OrderService.Delivery:output_type -> order.v1.EmptyMessage
	1,  // 27: order.v1.OrderService.Complete:output_type -> order.v1.EmptyMessage
	16, // 28: order.v1.OrderService.GetStatistics:output_type -> order.v1.StatisticsResponse
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
