// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: setmeal.proto

package setmealpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SetmealService_Create_FullMethodName           = "/setmeal.v1.SetmealService/Create"
	SetmealService_Deletes_FullMethodName          = "/setmeal.v1.SetmealService/Deletes"
	SetmealService_Update_FullMethodName           = "/setmeal.v1.SetmealService/Update"
	SetmealService_UpdateStatus_FullMethodName     = "/setmeal.v1.SetmealService/UpdateStatus"
	SetmealService_FindById_FullMethodName         = "/setmeal.v1.SetmealService/FindById"
	SetmealService_FindPage_FullMethodName         = "/setmeal.v1.SetmealService/FindPage"
	SetmealService_FindByCategoryId_FullMethodName = "/setmeal.v1.SetmealService/FindByCategoryId"
	SetmealService_FindDishById_FullMethodName     = "/setmeal.v1.SetmealService/FindDishById"
)

// SetmealServiceClient is the client API for SetmealService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SetmealServiceClient interface {
	Create(ctx context.Context, in *SetMealRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	Deletes(ctx context.Context, in *IdsMessage, opts ...grpc.CallOption) (*EmptyRequest, error)
	Update(ctx context.Context, in *SetMealRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	UpdateStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	FindById(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*SetMealResponse, error)
	FindPage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error)
	FindByCategoryId(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*FindByCategoryResponse, error)
	FindDishById(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*FindDishByIdResponse, error)
}

type setmealServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSetmealServiceClient(cc grpc.ClientConnInterface) SetmealServiceClient {
	return &setmealServiceClient{cc}
}

func (c *setmealServiceClient) Create(ctx context.Context, in *SetMealRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, SetmealService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setmealServiceClient) Deletes(ctx context.Context, in *IdsMessage, opts ...grpc.CallOption) (*EmptyRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, SetmealService_Deletes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setmealServiceClient) Update(ctx context.Context, in *SetMealRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, SetmealService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setmealServiceClient) UpdateStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, SetmealService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setmealServiceClient) FindById(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*SetMealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMealResponse)
	err := c.cc.Invoke(ctx, SetmealService_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setmealServiceClient) FindPage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageResponse)
	err := c.cc.Invoke(ctx, SetmealService_FindPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setmealServiceClient) FindByCategoryId(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*FindByCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindByCategoryResponse)
	err := c.cc.Invoke(ctx, SetmealService_FindByCategoryId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setmealServiceClient) FindDishById(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*FindDishByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindDishByIdResponse)
	err := c.cc.Invoke(ctx, SetmealService_FindDishById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetmealServiceServer is the server API for SetmealService service.
// All implementations must embed UnimplementedSetmealServiceServer
// for forward compatibility.
type SetmealServiceServer interface {
	Create(context.Context, *SetMealRequest) (*EmptyRequest, error)
	Deletes(context.Context, *IdsMessage) (*EmptyRequest, error)
	Update(context.Context, *SetMealRequest) (*EmptyRequest, error)
	UpdateStatus(context.Context, *StatusRequest) (*EmptyRequest, error)
	FindById(context.Context, *IdMessage) (*SetMealResponse, error)
	FindPage(context.Context, *PageRequest) (*PageResponse, error)
	FindByCategoryId(context.Context, *IdMessage) (*FindByCategoryResponse, error)
	FindDishById(context.Context, *IdMessage) (*FindDishByIdResponse, error)
	mustEmbedUnimplementedSetmealServiceServer()
}

// UnimplementedSetmealServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSetmealServiceServer struct{}

func (UnimplementedSetmealServiceServer) Create(context.Context, *SetMealRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSetmealServiceServer) Deletes(context.Context, *IdsMessage) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deletes not implemented")
}
func (UnimplementedSetmealServiceServer) Update(context.Context, *SetMealRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSetmealServiceServer) UpdateStatus(context.Context, *StatusRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedSetmealServiceServer) FindById(context.Context, *IdMessage) (*SetMealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedSetmealServiceServer) FindPage(context.Context, *PageRequest) (*PageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPage not implemented")
}
func (UnimplementedSetmealServiceServer) FindByCategoryId(context.Context, *IdMessage) (*FindByCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByCategoryId not implemented")
}
func (UnimplementedSetmealServiceServer) FindDishById(context.Context, *IdMessage) (*FindDishByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDishById not implemented")
}
func (UnimplementedSetmealServiceServer) mustEmbedUnimplementedSetmealServiceServer() {}
func (UnimplementedSetmealServiceServer) testEmbeddedByValue()                        {}

// UnsafeSetmealServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interfaces is not recommended, as added methods to SetmealServiceServer will
// result in compilation errors.
type UnsafeSetmealServiceServer interface {
	mustEmbedUnimplementedSetmealServiceServer()
}

func RegisterSetmealServiceServer(s grpc.ServiceRegistrar, srv SetmealServiceServer) {
	// If the following call pancis, it indicates UnimplementedSetmealServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SetmealService_ServiceDesc, srv)
}

func _SetmealService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetmealServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetmealService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetmealServiceServer).Create(ctx, req.(*SetMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetmealService_Deletes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetmealServiceServer).Deletes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetmealService_Deletes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetmealServiceServer).Deletes(ctx, req.(*IdsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetmealService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetmealServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetmealService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetmealServiceServer).Update(ctx, req.(*SetMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetmealService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetmealServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetmealService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetmealServiceServer).UpdateStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetmealService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetmealServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetmealService_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetmealServiceServer).FindById(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetmealService_FindPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetmealServiceServer).FindPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetmealService_FindPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetmealServiceServer).FindPage(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetmealService_FindByCategoryId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetmealServiceServer).FindByCategoryId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetmealService_FindByCategoryId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetmealServiceServer).FindByCategoryId(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetmealService_FindDishById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetmealServiceServer).FindDishById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetmealService_FindDishById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetmealServiceServer).FindDishById(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// SetmealService_ServiceDesc is the grpc.ServiceDesc for SetmealService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SetmealService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "setmeal.v1.SetmealService",
	HandlerType: (*SetmealServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SetmealService_Create_Handler,
		},
		{
			MethodName: "Deletes",
			Handler:    _SetmealService_Deletes_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SetmealService_Update_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _SetmealService_UpdateStatus_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _SetmealService_FindById_Handler,
		},
		{
			MethodName: "FindPage",
			Handler:    _SetmealService_FindPage_Handler,
		},
		{
			MethodName: "FindByCategoryId",
			Handler:    _SetmealService_FindByCategoryId_Handler,
		},
		{
			MethodName: "FindDishById",
			Handler:    _SetmealService_FindDishById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "setmeal.proto",
}
